// src/content/frases-del-dia.js
// Repertorio de frases del día (§5.3, Bloque 1 · RN-HOY-02).
//
// Va en `content/` y no dentro del componente ni dentro de la spec: es material
// editorial, crece con el tiempo y se revisa aparte del código que lo pinta.
//
// **Tamaño del repertorio.** RN-HOY-02 pide que una frase no se repita en 365
// días. Este repertorio tiene 200 entradas, así que la no repetición está
// garantizada durante 200 días. `diasSinRepetir` lo dice en voz alta para que
// nadie tenga que contarlas a mano.
//
// **Dos tipos de entrada** (`tipo`):
//   · 'original' — redacción propia de Strivo inspirada en una obra antigua.
//     Se muestra SIN comillas. Atribución: "Versión Strivo inspirada en X".
//   · 'cita' — reproducción textual de una obra en dominio público (autor
//     fallecido hace más de cien años y obra publicada antes de 1931). Se
//     muestra ENTRE COMILLAS. Atribución: "Autor · Obra".
//
// **Reglas editoriales que no se pueden romper** (ver el documento fuente
// `docs/200-frases-fuentes.md`):
//   · No convertir una 'original' en cita: nunca "dijo" ni "escribió".
//   · No mostrar solo el nombre del autor tras un guion en una 'original'.
//   · No corregir ni modernizar el texto de una 'cita' sin cotejarlo con la
//     edición de referencia. La puntuación y las mayúsculas son de la edición.
//   · No convertir una cita en eslogan, nombre de función o campaña sin
//     revisar antes posibles marcas.
//
// **Saltos de verso.** Las citas en verso llevan `\n`. El componente que las
// pinta necesita `white-space: pre-line` para respetarlos.
//
// **Ninguna frase lleva marca de género en el trato a la persona usuaria.**
// Están redactadas para que no haga falta el helper de §3.6.5: una frase
// distinta cada día en tres versiones sería mantener tres repertorios.
//
// **Orden.** Las entradas van intercaladas a propósito: el tema rota en el
// ciclo gratitud → calma → identidad → aceptación → esfuerzo, y el tipo
// alterna cada vuelta. Como `fraseDelDia()` recorre el array por índice de
// día, agruparlas por tema daría cuarenta días consecutivos del mismo tema.
// Al añadir entradas nuevas, respetar el ciclo o reordenar el array entero.
//
// Temas (§5.3): gratitud · calma · esfuerzo · identidad · aceptacion.

/** Temas con los que se etiqueta cada frase. */
export const TEMAS = Object.freeze(['gratitud', 'calma', 'esfuerzo', 'identidad', 'aceptacion'])

/** Tipos de entrada: redacción propia de Strivo o cita textual en dominio público. */
export const TIPOS = Object.freeze(['original', 'cita'])

/**
 * Temas que se retiran cuando el ánimo reciente es bajo (§5.3, Bloque 1).
 * A alguien que lleva tres días agotado no se le abre el día pidiéndole
 * constancia: sería la app diciéndole que el problema es que no se esfuerza.
 */
export const TEMAS_DE_RENDIMIENTO = Object.freeze(['esfuerzo'])

export const FRASES = Object.freeze([
  {
    id: 'O-001',
    texto: 'Agradecer no agranda lo recibido; agranda nuestra capacidad de recibirlo.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre los beneficios, libro I',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-021',
    texto: 'Cuando el mundo pese, vuelve a ese lugar tranquilo que existe dentro de ti.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, IV.3',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-041',
    texto: 'Tu mente va tomando la forma de aquello que alimentas con frecuencia.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, V.16',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-061',
    texto: 'Puedo recibir este momento como parte del mundo al que pertenezco.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, IV.23',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-081',
    texto: 'Levántate para hacer tu parte en la vida humana de hoy.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, V.1',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'C-001',
    texto: 'Muy cerca de mi ocaso, yo te bendigo, Vida,',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-021',
    texto: 'Nada te turbe, nada te espante;',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Nada te turbe',
    atribucion: 'Teresa de Ávila · Nada te turbe',
  },
  {
    id: 'C-041',
    texto: 'Yo soy un hombre sincero\nDe donde crece la palma.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, I',
    atribucion: 'José Martí · Versos sencillos, I',
  },
  {
    id: 'C-061',
    texto: 'Que se cumpla el destino, que Dios dicte su fallo.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'Expectación, en Elevación',
    atribucion: 'Amado Nervo · Expectación, en Elevación',
  },
  {
    id: 'C-081',
    texto:
      'La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-002',
    texto: 'Recuerda el bien que recibiste y suelta la necesidad de recordar el que hiciste.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre los beneficios, libro I',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-022',
    texto: 'Si sueltas el juicio que te lastima, también empieza a soltarse la herida.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, IV.7',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-042',
    texto: 'No gastes la vida explicando cómo es una buena persona: encárnala.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, X.16',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-062',
    texto: 'Ama el momento que llegó, porque es el único desde el que puedes vivir.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VII.57',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-082',
    texto: 'Si algo es bueno y necesario, el clima del día no cambia su valor.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VI.2',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'C-002',
    texto: 'porque nunca me diste ni esperanza fallida\nni trabajos injustos ni pena inmerecida.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-022',
    texto: 'todo se pasa, Dios no se muda;',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Nada te turbe',
    atribucion: 'Teresa de Ávila · Nada te turbe',
  },
  {
    id: 'C-042',
    texto: 'Yo vengo de todas partes,\nY hacia todas partes voy:',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, I',
    atribucion: 'José Martí · Versos sencillos, I',
  },
  {
    id: 'C-062',
    texto:
      'Mientras, yo, de rodillas, oro, espero y me callo,\npara oír la palabra que el ABISMO dirá...',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'Expectación, en Elevación',
    atribucion: 'Amado Nervo · Expectación, en Elevación',
  },
  {
    id: 'C-082',
    texto: 'La diligencia es madre de la buena ventura.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-003',
    texto: 'Un gesto vale menos por lo que entrega que por la intención con la que llega.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre los beneficios, libro I',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-023',
    texto: 'Si algo te altera, regresa a ti tan pronto como puedas.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VI.11',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-043',
    texto: 'No entregues tu tiempo a imaginar la vida ajena; ocúpate de vivir la tuya.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, III.4',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-063',
    texto: 'No cargues a la vez el pasado, el futuro y este instante; hoy basta con hoy.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VIII.36',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-083',
    texto: 'Haz cada acción con presencia, como si también ahí se expresara tu carácter.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VIII.32',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'C-003',
    texto: 'que yo fui el arquitecto de mi propio destino;',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-023',
    texto: 'la paciencia todo lo alcanza.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Nada te turbe',
    atribucion: 'Teresa de Ávila · Nada te turbe',
  },
  {
    id: 'C-043',
    texto: 'Arte soy entre las artes,\nEn los montes, monte soy.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, I',
    atribucion: 'José Martí · Versos sencillos, I',
  },
  {
    id: 'C-063',
    texto: 'Hay tanto amor en mi alma, que no queda\nni el rincón más estrecho para el odio.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'Tanto amor, en Elevación',
    atribucion: 'Amado Nervo · Tanto amor, en Elevación',
  },
  {
    id: 'C-083',
    texto: 'Cada uno es artífice de su ventura.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-004',
    texto: 'La gratitud comienza mientras la bondad todavía está ocurriendo.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre los beneficios, libro II',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-024',
    texto: 'Retirarte un momento hacia dentro puede devolverte a lo importante.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VII.28',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-044',
    texto: 'Cuida que el papel que desempeñas no borre a la persona que quieres ser.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VI.30',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-064',
    texto: 'Si una experiencia puede ser atravesada, también puede enseñarte cómo sostenerla.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, X.3',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-084',
    texto: 'Cada dificultad trae una oportunidad de ejercitar una capacidad.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 10',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'C-004',
    texto: 'cuando planté rosales coseché siempre rosas.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-024',
    texto: 'No está la cosa en pensar mucho, sino en amar mucho.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Las moradas, IV.1.7',
    atribucion: 'Teresa de Ávila · Las moradas, IV.1.7',
  },
  {
    id: 'C-044',
    texto: 'Mi verso es como un puñal\nQue por el puño echa flor:',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, V',
    atribucion: 'José Martí · Versos sencillos, V',
  },
  {
    id: 'C-064',
    texto: 'Todo lo olvido,\nporque soy sólo corazón,',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'Tanto amor, en Elevación',
    atribucion: 'Amado Nervo · Tanto amor, en Elevación',
  },
  {
    id: 'C-084',
    texto: 'El que lee mucho y anda mucho, vee mucho y sabe mucho.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-005',
    texto: 'No midas tu vida por lo que faltó, sino por lo que ya te fue concedido.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre los beneficios, libro III',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-025',
    texto: 'Una mente ordenada puede convertirse en su propio refugio.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VIII.48',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-045',
    texto: 'No eliges todos tus papeles, pero sí la dignidad con la que los interpretas.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 17',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-065',
    texto: 'Distinguir lo que depende de ti es el comienzo de una libertad serena.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 1',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-085',
    texto: 'Ante un impulso que te aleja de ti, una pausa ya es una forma de fuerza.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 34',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'C-005',
    texto: '¡mas tú no me dijiste que mayo fuese eterno!',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-025',
    texto: 'Y así lo que más os despertare a amar, eso haced.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Las moradas, IV.1.7',
    atribucion: 'Teresa de Ávila · Las moradas, IV.1.7',
  },
  {
    id: 'C-045',
    texto: 'Mi verso es de un verde claro\nY de un carmín encendido:',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, V',
    atribucion: 'José Martí · Versos sencillos, V',
  },
  {
    id: 'C-065',
    texto: 'Tú en la aurora que canta y en la noche que piensa;',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'Tú, en Elevación',
    atribucion: 'Amado Nervo · Tú, en Elevación',
  },
  {
    id: 'C-085',
    texto: 'El que hoy cae puede levantarse mañana.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-006',
    texto: 'La forma más clara de agradecer es vivir bien con lo recibido.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre los beneficios, libro II',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-026',
    texto: 'No siempre te inquieta lo que sucede, sino la historia que construyes sobre ello.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 5',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-046',
    texto: 'Ser fiel a tus principios puede parecer extraño antes de sentirse verdadero.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 23',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-066',
    texto: 'Antes de empezar algo, acepta también la naturaleza real de lo que implica.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 4',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-086',
    texto: 'No esperes sentirte listo para comenzar a vivir según tus principios.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 51',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'C-006',
    texto: 'y en cambio tuve algunas santamente serenas...',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-026',
    texto: 'Finjamos que soy feliz,\nTriste pensamiento, un rato;',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Finjamos que soy feliz',
    atribucion: 'Sor Juana Inés de la Cruz · Finjamos que soy feliz',
  },
  {
    id: 'C-046',
    texto: 'Mi verso, breve y sincero,\nEs del vigor del acero',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, V',
    atribucion: 'José Martí · Versos sencillos, V',
  },
  {
    id: 'C-066',
    texto:
      'Nadie mira la rosa que nació en el desierto;\nmas ella, ufana, erguida, muestra el cáliz abierto,',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'El castaño no sabe..., en Elevación',
    atribucion: 'Amado Nervo · El castaño no sabe..., en Elevación',
  },
  {
    id: 'C-086',
    texto: 'Bien predica quien bien vive.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-007',
    texto: 'Reconocer el bien recibido es una de las responsabilidades más humanas.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Cicerón',
    fuente: 'Sobre los deberes, I.47',
    atribucion: 'Versión Strivo inspirada en Cicerón',
  },
  {
    id: 'O-027',
    texto: 'La calma aparece cuando dejas de exigir que la realidad siga tu guion.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 8',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-047',
    texto: 'Crecer también es dejar de medir tu valor con elogios y culpas externas.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 48',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-067',
    texto: 'Desear que lo ocurrido sea distinto prolonga una lucha que ya terminó.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 8',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-087',
    texto: 'Aprendes a hacer lo justo practicando actos justos.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, II.1',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'C-007',
    texto: 'Amé, fui amado, el sol acarició mi faz.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-027',
    texto: 'Si os imagináis dichoso\nNo seréis tan desdichado.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Finjamos que soy feliz',
    atribucion: 'Sor Juana Inés de la Cruz · Finjamos que soy feliz',
  },
  {
    id: 'C-047',
    texto: '¡Arpa soy, salterio soy\nDonde vibra el Universo;',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, XVII',
    atribucion: 'José Martí · Versos sencillos, XVII',
  },
  {
    id: 'C-067',
    texto: 'Siento que algo solemne va a llegar en mi vida.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'Expectación, en Elevación',
    atribucion: 'Amado Nervo · Expectación, en Elevación',
  },
  {
    id: 'C-087',
    texto: 'Las obras que se hacen declaran la voluntad que tiene el que las hace.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-008',
    texto: 'La gratitud no camina sola: de ella nacen muchas otras virtudes.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Cicerón',
    fuente: 'Discurso en defensa de Plancio, 80',
    atribucion: 'Versión Strivo inspirada en Cicerón',
  },
  {
    id: 'O-028',
    texto: 'Ante cada dificultad, pregúntate qué capacidad tuya puede acompañarte.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 10',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-048',
    texto: 'No pospongas más a la persona que sabes que puedes comenzar a ser.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 51',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-068',
    texto: 'Una limitación puede afectar una parte de ti sin definirte por completo.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 9',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-088',
    texto: 'Tu carácter no aparece de una vez: se forma en lo que eliges una y otra vez.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, III.5',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'C-008',
    texto: '¡Vida, nada me debes! ¡Vida, estamos en paz!',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Amado Nervo',
    fuente: 'En paz, en Elevación',
    atribucion: 'Amado Nervo · En paz, en Elevación',
  },
  {
    id: 'C-028',
    texto: 'Sírvame el entendimiento\nAlguna vez de descanso',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Finjamos que soy feliz',
    atribucion: 'Sor Juana Inés de la Cruz · Finjamos que soy feliz',
  },
  {
    id: 'C-048',
    texto: 'Todo el mundo es opiniones,\nDe pareceres tan varios,',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Finjamos que soy feliz',
    atribucion: 'Sor Juana Inés de la Cruz · Finjamos que soy feliz',
  },
  {
    id: 'C-068',
    texto: 'El verdadero humilde ha de ir contento por el camino que le llevare el Señor.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Camino de perfección, 15.2',
    atribucion: 'Teresa de Ávila · Camino de perfección, 15.2',
  },
  {
    id: 'C-088',
    texto: 'La firmeza en los amantes es la parte más preciada.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-009',
    texto: 'La amistad ilumina la alegría y vuelve más liviano el dolor.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Cicerón',
    fuente: 'Sobre la amistad, 22',
    atribucion: 'Versión Strivo inspirada en Cicerón',
  },
  {
    id: 'O-029',
    texto: 'Las palabras ajenas solo entran hasta donde tu juicio les abre la puerta.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 20',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-049',
    texto: 'Las virtudes se vuelven tuyas cuando las practicas.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, II.1',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'O-069',
    texto: 'No puedes perder una batalla en la que decides no entregar tu paz.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 19',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-089',
    texto: 'Una vida plena no es solo una intención; es una manera constante de actuar.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, I.7',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'C-009',
    texto: 'Quien a Dios tiene nada le falta.\nSólo Dios basta.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Nada te turbe',
    atribucion: 'Teresa de Ávila · Nada te turbe',
  },
  {
    id: 'C-029',
    texto:
      'Especular las desdichas\nY examinar los presagios.\nSólo sirve de que el mal\nCrezca con anticiparlo.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Finjamos que soy feliz',
    atribucion: 'Sor Juana Inés de la Cruz · Finjamos que soy feliz',
  },
  {
    id: 'C-049',
    texto:
      'Yo no estudio para escribir, ni menos para enseñar (que fuera en mí desmedida soberbia), sino sólo por ver si con estudiar ignoro menos.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Respuesta a sor Filotea de la Cruz',
    atribucion: 'Sor Juana Inés de la Cruz · Respuesta a sor Filotea de la Cruz',
  },
  {
    id: 'C-069',
    texto: 'No es saber, saber hacer\nDiscursos sutiles vanos.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Finjamos que soy feliz',
    atribucion: 'Sor Juana Inés de la Cruz · Finjamos que soy feliz',
  },
  {
    id: 'C-089',
    texto: 'Vale más buena esperanza que ruin posesión.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'O-010',
    texto: 'Lo bueno se vuelve más pleno cuando encuentra con quién compartirse.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Cartas a Lucilio, carta 6',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-030',
    texto: 'Sufrimos muchas veces en la imaginación antes de que algo ocurra.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Cartas a Lucilio, carta 13',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-050',
    texto: 'Tus actos repetidos van educando tu carácter.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, II.4',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'O-070',
    texto: 'A veces, ceder un poco es la manera de conservarte entero.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 22',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-090',
    texto: 'Cultiva con cuidado lo más lúcido que hay en ti.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, X.7',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'C-010',
    texto: 'que sólo amor es el que da valor a todas las cosas;',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Exclamaciones del alma a Dios, V',
    atribucion: 'Teresa de Ávila · Exclamaciones del alma a Dios, V',
  },
  {
    id: 'C-030',
    texto: 'El No y el Sí son breves de decir y piden mucho pensar.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 70',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 70',
  },
  {
    id: 'C-050',
    texto: 'Yo no estimo tesoros ni riquezas;',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'En perseguirme, Mundo, ¿qué interesas?',
    atribucion: 'Sor Juana Inés de la Cruz · En perseguirme, Mundo, ¿qué interesas?',
  },
  {
    id: 'C-070',
    texto: 'Que el saber consiste sólo\nEn elegir lo más sano.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'Finjamos que soy feliz',
    atribucion: 'Sor Juana Inés de la Cruz · Finjamos que soy feliz',
  },
  {
    id: 'C-090',
    texto: 'Harto presto, si bien.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 57',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 57',
  },
  {
    id: 'O-011',
    texto: 'Mira las cualidades de quienes amas y deja que despierten lo mejor de ti.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Marco Aurelio',
    fuente: 'Meditaciones, VI.48',
    atribucion: 'Versión Strivo inspirada en Marco Aurelio',
  },
  {
    id: 'O-031',
    texto: 'Cambiar de lugar no aquieta una mente que no ha vuelto a sí misma.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Cartas a Lucilio, carta 28',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-051',
    texto: 'La fortaleza también sabe elegir la medida justa.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, II.6',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'O-071',
    texto: 'Lo vivo sabe ser flexible; no necesita endurecerse para sostenerse.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 76',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-091',
    texto: 'Aprender se vuelve alegría cuando encuentra un lugar en la práctica.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, I.1',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'C-011',
    texto: 'entre los pucheros anda el Señor',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Libro de las fundaciones, 5.8',
    atribucion: 'Teresa de Ávila · Libro de las fundaciones, 5.8',
  },
  {
    id: 'C-031',
    texto: 'Saber ceder al tiempo es exceder.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 220',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 220',
  },
  {
    id: 'C-051',
    texto: 'poner riquezas en mi pensamiento\nque no mi pensamiento en las riquezas.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Sor Juana Inés de la Cruz',
    fuente: 'En perseguirme, Mundo, ¿qué interesas?',
    atribucion: 'Sor Juana Inés de la Cruz · En perseguirme, Mundo, ¿qué interesas?',
  },
  {
    id: 'C-071',
    texto: 'Podrá no haber poetas; pero siempre\nHabrá poesía.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Gustavo Adolfo Bécquer',
    fuente: 'Rimas, IV',
    atribucion: 'Gustavo Adolfo Bécquer · Rimas, IV',
  },
  {
    id: 'C-091',
    texto:
      'Lo que mucho vale, mucho cuesta, que aun el más precioso de los metales es el más tardo y más grave.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 57',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 57',
  },
  {
    id: 'O-012',
    texto: 'A veces no has perdido algo: simplemente lo has devuelto.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 11',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-032',
    texto: 'La serenidad no es inmovilidad: es una mente que conserva su dirección.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre la tranquilidad del ánimo, II',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-052',
    texto: 'Elegir bien es convertir una reflexión en dirección.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, III.3',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'O-072',
    texto: 'La suavidad del agua vence sin dejar de ser agua.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 78',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-092',
    texto: 'Estudiar sin reflexionar te pierde; reflexionar sin aprender te deja sin suelo.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, II.15',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'C-012',
    texto: 'tratar de amistad, estando muchas veces tratando a solas con quien sabemos nos ama.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Teresa de Ávila',
    fuente: 'Libro de la vida, 8.5',
    atribucion: 'Teresa de Ávila · Libro de la vida, 8.5',
  },
  {
    id: 'C-032',
    texto: 'No tenemos cosa nuestra sino el tiempo.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 247',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 247',
  },
  {
    id: 'C-052',
    texto:
      'No se nace hecho: vase de cada día perfeccionando en la persona, en el empleo, hasta llegar al punto del consumado ser.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 6',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 6',
  },
  {
    id: 'C-072',
    texto: 'Mientras haya un misterio para el hombre,\n¡Habrá poesía!',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Gustavo Adolfo Bécquer',
    fuente: 'Rimas, IV',
    atribucion: 'Gustavo Adolfo Bécquer · Rimas, IV',
  },
  {
    id: 'C-092',
    texto: 'Menos dañosa es la mala ejecución que la irresolución.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 72',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 72',
  },
  {
    id: 'O-013',
    texto: 'Recibe lo que llega como en una mesa: sin arrebatar y sin despreciar.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 15',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-033',
    texto: 'La paz que buscas debe poder acompañarte a donde vayas.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Cartas a Lucilio, carta 104',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-053',
    texto: 'Admira lo valioso en otros y úsalo para mirarte con honestidad.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, IV.17',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'O-073',
    texto: 'Cuando intentas controlar cada cosa, también puedes impedirle respirar.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 29',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-093',
    texto: 'Entre varias personas siempre puede haber alguien de quien aprender.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, VII.22',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'C-013',
    texto: 'Todo es hermoso y constante,\nTodo es música y razón,',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, I',
    atribucion: 'José Martí · Versos sencillos, I',
  },
  {
    id: 'C-033',
    texto: 'Saber renovar el genio con la naturaleza y con el arte.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 276',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 276',
  },
  {
    id: 'C-053',
    texto: 'No basta lo entendido, deséase lo genial.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 2',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 2',
  },
  {
    id: 'C-073',
    texto: 'Que el alma que hablar puede con los ojos,\nTambién puede besar con la mirada.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Gustavo Adolfo Bécquer',
    fuente: 'Rimas, XX',
    atribucion: 'Gustavo Adolfo Bécquer · Rimas, XX',
  },
  {
    id: 'C-093',
    texto: 'Las palabras han de ser prendas de las obras.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 166',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 166',
  },
  {
    id: 'O-014',
    texto: 'Apreciar algo también es recordar que no nos pertenece para siempre.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Epicteto',
    fuente: 'Enquiridión, 3',
    atribucion: 'Versión Strivo inspirada en Epicteto',
  },
  {
    id: 'O-034',
    texto: 'Cuando aparezca la ira, dale tiempo antes de darle voz.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Séneca',
    fuente: 'Sobre la ira, III.12',
    atribucion: 'Versión Strivo inspirada en Séneca',
  },
  {
    id: 'O-054',
    texto: 'Trata a los demás desde el mismo respeto que deseas recibir.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, XV.24',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'O-074',
    texto: 'La sabiduría no se aferra ni a la alegría ni a la tristeza: aprende de ambas.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Dhammapada',
    fuente: 'verso 83',
    atribucion: 'Versión Strivo inspirada en Dhammapada',
  },
  {
    id: 'O-094',
    texto: 'Un error que decides corregir deja de gobernar tu camino.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, XV.30',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'C-014',
    texto: 'Con los pobres de la tierra\nQuiero yo mi suerte echar:',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, III',
    atribucion: 'José Martí · Versos sencillos, III',
  },
  {
    id: 'C-034',
    texto: 'Ayer se fue, mañana no ha llegado;',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Francisco de Quevedo',
    fuente: 'Represéntase la brevedad de lo que se vive',
    atribucion: 'Francisco de Quevedo · Represéntase la brevedad de lo que se vive',
  },
  {
    id: 'C-054',
    texto: 'El saber y el valor alternan grandeza.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 4',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 4',
  },
  {
    id: 'C-074',
    texto: 'soy un fue, y un será, y un es cansado.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Francisco de Quevedo',
    fuente: 'Represéntase la brevedad de lo que se vive',
    atribucion: 'Francisco de Quevedo · Represéntase la brevedad de lo que se vive',
  },
  {
    id: 'C-094',
    texto: 'La presteza es madre de la dicha.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 53',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 53',
  },
  {
    id: 'O-015',
    texto: 'Quien reconoce lo suficiente descubre una forma de riqueza.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 33',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-035',
    texto: 'El agua turbia recupera su claridad cuando se le permite estar quieta.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 15',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-055',
    texto: 'Una persona íntegra comienza por exigirse a sí misma.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, XV.21',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'O-075',
    texto: 'Todo cambia; recordar esto puede suavizar la resistencia.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Dhammapada',
    fuente: 'verso 277',
    atribucion: 'Versión Strivo inspirada en Dhammapada',
  },
  {
    id: 'O-095',
    texto: 'La acción es tuya; el resultado, no siempre.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'II.47',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'C-015',
    texto: 'El arroyo de la sierra\nMe complace más que el mar.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, III',
    atribucion: 'José Martí · Versos sencillos, III',
  },
  {
    id: 'C-035',
    texto: 'hoy se está yendo sin parar un punto:',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Francisco de Quevedo',
    fuente: 'Represéntase la brevedad de lo que se vive',
    atribucion: 'Francisco de Quevedo · Represéntase la brevedad de lo que se vive',
  },
  {
    id: 'C-055',
    texto:
      'No hay mayor señorío que el de sí mismo, de sus afectos, que llega a ser triunfo del albedrío.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 8',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 8',
  },
  {
    id: 'C-075',
    texto: 'Donde una puerta se cierra, otra se abre.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-095',
    texto: 'No hay mejor compañía en los grandes aprietos que un buen corazón.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 167',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 167',
  },
  {
    id: 'O-016',
    texto: 'Saber detenerse protege la alegría de lo que ya existe.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 44',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-036',
    texto: 'Haz espacio dentro de ti y deja que el silencio vuelva a ordenar.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 16',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-056',
    texto: 'Preocúpate menos por ser reconocido y más por ser digno de reconocimiento.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Confucio',
    fuente: 'Analectas, I.16',
    atribucion: 'Versión Strivo inspirada en Confucio',
  },
  {
    id: 'O-076',
    texto: 'Aceptar que algo duele no significa renunciar a atravesarlo.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Dhammapada',
    fuente: 'verso 278',
    atribucion: 'Versión Strivo inspirada en Dhammapada',
  },
  {
    id: 'O-096',
    texto: 'Actúa con dedicación, sin convertir el fruto en una condición para estar en paz.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'III.19',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'C-016',
    texto: 'Cultivo una rosa blanca\nEn julio como enero,',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, XXXIX',
    atribucion: 'José Martí · Versos sencillos, XXXIX',
  },
  {
    id: 'C-036',
    texto: 'Retirado en la paz de estos desiertos,\nCon pocos, pero doctos libros juntos,',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Francisco de Quevedo',
    fuente: 'Desde la Torre',
    atribucion: 'Francisco de Quevedo · Desde la Torre',
  },
  {
    id: 'C-056',
    texto: 'Principio es de corregirse el conocerse.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 69',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 69',
  },
  {
    id: 'C-076',
    texto:
      'La verdad adelgaza y no quiebra, y siempre anda sobre la mentira como el aceite sobre el agua.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-096',
    texto: 'Saber, o escuchar a quien sabe.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 176',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 176',
  },
  {
    id: 'O-017',
    texto: 'La satisfacción serena vale más que la abundancia inquieta.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 46',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-037',
    texto: 'La quietud puede sostenerte incluso cuando todo alrededor se mueve.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 26',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-057',
    texto: 'Tu identidad se fortalece cuando tus actos y tus valores dejan de contradecirse.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Aristóteles',
    fuente: 'Ética nicomáquea, II.4',
    atribucion: 'Versión Strivo inspirada en Aristóteles',
  },
  {
    id: 'O-077',
    texto: 'Las sensaciones llegan y se van; respira mientras pasa la ola.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'II.14',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'O-097',
    texto: 'Puedes ayudarte a elevarte; no necesitas convertirte en tu propio obstáculo.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'VI.5',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'C-017',
    texto: 'Cardo ni ortiga cultivo;\nCultivo la rosa blanca.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, XXXIX',
    atribucion: 'José Martí · Versos sencillos, XXXIX',
  },
  {
    id: 'C-037',
    texto: 'En fuga irrevocable huye la hora;',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Francisco de Quevedo',
    fuente: 'Desde la Torre',
    atribucion: 'Francisco de Quevedo · Desde la Torre',
  },
  {
    id: 'C-057',
    texto: 'El varón cuerdo siempre fue el mismo en todo lo perfecto.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 71',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 71',
  },
  {
    id: 'C-077',
    texto:
      'El tiempo, descubridor de todas las cosas, no se deja ninguna que no las saque a la luz del sol.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-097',
    texto: 'La diligencia allana la imposibilidad.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 204',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 204',
  },
  {
    id: 'O-018',
    texto: 'La salud es un regalo; sentir que basta es una riqueza.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Dhammapada',
    fuente: 'verso 204',
    atribucion: 'Versión Strivo inspirada en Dhammapada',
  },
  {
    id: 'O-038',
    texto: 'Cuanto menos fuerzas cada cosa, más espacio das para que encuentre su lugar.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Laozi',
    fuente: 'Tao Te Ching, 57',
    atribucion: 'Versión Strivo inspirada en Laozi',
  },
  {
    id: 'O-058',
    texto: 'Eres responsable de tus obras, y tus obras también terminan hablándote de quién eres.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote, primera parte, capítulo 47',
    atribucion: 'Versión Strivo inspirada en Miguel de Cervantes',
  },
  {
    id: 'O-078',
    texto: 'Haz lo que te corresponde sin entregar tu equilibrio al resultado.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'II.48',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'O-098',
    texto: 'Volver a intentarlo también es entrenar la mente.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'VI.26',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'C-018',
    texto: 'Hoy la tierra y los cielos me sonrien,',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Gustavo Adolfo Bécquer',
    fuente: 'Rimas, XVII',
    atribucion: 'Gustavo Adolfo Bécquer · Rimas, XVII',
  },
  {
    id: 'C-038',
    texto: 'Los suspiros son aire, y van al aire.\nLas lágrimas son agua, y van al mar.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Gustavo Adolfo Bécquer',
    fuente: 'Rimas, XXXVIII',
    atribucion: 'Gustavo Adolfo Bécquer · Rimas, XXXVIII',
  },
  {
    id: 'C-058',
    texto: 'Diferenciar el hombre de palabras del de obras.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 166',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 166',
  },
  {
    id: 'C-078',
    texto: 'No huye el que se retira.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-098',
    texto: 'Saber hacer el bien: poco, y muchas veces.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'Baltasar Gracián',
    fuente: 'Oráculo manual y arte de prudencia, af. 255',
    atribucion: 'Baltasar Gracián · Oráculo manual y arte de prudencia, af. 255',
  },
  {
    id: 'O-019',
    texto: 'También es motivo de alegría contar con buena compañía en el camino.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Dhammapada',
    fuente: 'verso 331',
    atribucion: 'Versión Strivo inspirada en Dhammapada',
  },
  {
    id: 'O-039',
    texto: 'Una mente firme puede recibir el viento sin perder su centro.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Dhammapada',
    fuente: 'verso 81',
    atribucion: 'Versión Strivo inspirada en Dhammapada',
  },
  {
    id: 'O-059',
    texto: 'Cada decisión participa, poco a poco, en la construcción de tu ventura.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote, segunda parte, capítulo 66',
    atribucion: 'Versión Strivo inspirada en Miguel de Cervantes',
  },
  {
    id: 'O-079',
    texto: 'Como el océano recibe los ríos, puedes recibir lo que llega sin perder tu profundidad.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'II.70',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'O-099',
    texto: 'Cuando una puerta se cierra, conserva la atención para reconocer la que se abre.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote, primera parte, capítulo 21',
    atribucion: 'Versión Strivo inspirada en Miguel de Cervantes',
  },
  {
    id: 'C-019',
    texto:
      'La música compone los ánimos descompuestos y alivia los trabajos que nacen del espíritu.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-039',
    texto: 'No hay memoria a quien el tiempo no acabe, ni dolor que muerte no le consuma.',
    tema: 'calma',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-059',
    texto: 'Cada uno es hijo de sus obras.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-079',
    texto: 'Siempre deja la ventura una puerta abierta en las desdichas, para dar remedio a ellas.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-099',
    texto: 'Antes que luz es carbón.',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, I',
    atribucion: 'José Martí · Versos sencillos, I',
  },
  {
    id: 'O-020',
    texto: 'La paciencia abre espacio hasta que lo esencial vuelve a bastar.',
    tema: 'gratitud',
    tipo: 'original',
    autor: 'Teresa de Ávila',
    fuente: 'Nada te turbe',
    atribucion: 'Versión Strivo inspirada en Teresa de Ávila',
  },
  {
    id: 'O-040',
    texto: 'Cuando el interior está en paz, las palabras y los actos también descansan.',
    tema: 'calma',
    tipo: 'original',
    autor: 'Dhammapada',
    fuente: 'verso 96',
    atribucion: 'Versión Strivo inspirada en Dhammapada',
  },
  {
    id: 'O-060',
    texto: 'Naciste con una vida propia; no tienes que convertirla en respuesta a deseos ajenos.',
    tema: 'identidad',
    tipo: 'original',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote, primera parte, capítulo 14',
    atribucion: 'Versión Strivo inspirada en Miguel de Cervantes',
  },
  {
    id: 'O-080',
    texto: 'Cada vez que tu mente se disperse, acompáñala con paciencia de regreso.',
    tema: 'aceptacion',
    tipo: 'original',
    autor: 'Bhagavad Gita',
    fuente: 'VI.26',
    atribucion: 'Versión Strivo inspirada en Bhagavad Gita',
  },
  {
    id: 'O-100',
    texto: 'La diligencia acerca a la realidad aquello que un buen deseo apenas comienza.',
    tema: 'esfuerzo',
    tipo: 'original',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote, primera parte, capítulo 46',
    atribucion: 'Versión Strivo inspirada en Miguel de Cervantes',
  },
  {
    id: 'C-020',
    texto: 'La buena y verdadera amistad no puede ni debe de ser sospechosa en nada.',
    tema: 'gratitud',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-040',
    texto: 'Duermo en mi cama de roca\nMi sueño dulce y profundo:',
    tema: 'calma',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, III',
    atribucion: 'José Martí · Versos sencillos, III',
  },
  {
    id: 'C-060',
    texto: 'La pluma es lengua del alma.',
    tema: 'identidad',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-080',
    texto: 'El principio de la salud está en conocer la enfermedad.',
    tema: 'aceptacion',
    tipo: 'cita',
    autor: 'Miguel de Cervantes',
    fuente: 'Don Quijote de la Mancha',
    atribucion: 'Miguel de Cervantes · Don Quijote de la Mancha',
  },
  {
    id: 'C-100',
    texto: 'Oculto en mi pecho bravo\nLa pena que me lo hiere:',
    tema: 'esfuerzo',
    tipo: 'cita',
    autor: 'José Martí',
    fuente: 'Versos sencillos, I',
    atribucion: 'José Martí · Versos sencillos, I',
  },
])

/** Días que el repertorio actual aguanta sin repetir una frase (RN-HOY-02). */
export function diasSinRepetir(frases = FRASES) {
  return frases.length
}

/** Días transcurridos desde el 1 de enero de 1970, a partir de 'YYYY-MM-DD'. */
function diasDesdeEpoca(dateKey) {
  const [year, month, day] = String(dateKey ?? '')
    .split('-')
    .map(Number)
  if (!year || !month || !day) return 0
  return Math.floor(Date.UTC(year, month - 1, day) / 86400000)
}

/**
 * La frase de un día concreto.
 *
 * Determinista: la misma fecha devuelve siempre la misma frase, en el
 * dispositivo y sin red (§5.2, "Persistencia"). No hay azar ni estado guardado
 * que pueda desincronizarse.
 *
 * @param {string} dateKey - 'YYYY-MM-DD'
 * @param {object} [opciones]
 * @param {boolean} [opciones.animoBajoReciente] - Retira los temas de
 *        rendimiento (§5.3, Bloque 1). Por defecto, false.
 * @returns {{id: string, texto: string, tema: string, tipo: string, autor: string, fuente: string, atribucion: string}}
 */
export function fraseDelDia(dateKey, { animoBajoReciente = false } = {}) {
  const repertorio = animoBajoReciente
    ? FRASES.filter((frase) => !TEMAS_DE_RENDIMIENTO.includes(frase.tema))
    : FRASES

  const indice =
    ((diasDesdeEpoca(dateKey) % repertorio.length) + repertorio.length) % repertorio.length
  return repertorio[indice]
}

/**
 * Las cadenas de una frase que tienen que pasar el léxico de §3.6.
 *
 * **Una cita no se revisa por su texto, y no es una relajación de la regla: es
 * lo que una cita es.** Es texto histórico en dominio público, reproducido de
 * una edición de referencia; corregirlo para que pase el léxico lo dejaría de
 * ser. Nervo escribió «¡Vida, estamos en paz!» con esa exclamación, y Strivo
 * no la firma: la atribuye. Lo que sí se revisa siempre es la `atribucion`
 * —esa la escribimos nosotros— y el `texto` de las originales, que es voz de
 * Strivo aunque se inspire en otro.
 *
 * Vive aquí, junto a los datos, y no dentro del script de léxico ni dentro de
 * la prueba: los dos la consumen, y dos copias de la misma regla envejecen
 * distinto (§11, "Dónde vive cada regla").
 *
 * @param {{texto?: string, tipo?: string, atribucion?: string}} frase
 * @returns {string[]} Las cadenas revisables, sin huecos.
 */
export function revisablesDe(frase) {
  if (!frase) return []
  const texto = frase.tipo === 'cita' ? '' : frase.texto
  return [texto, frase.atribucion].filter((cadena) => typeof cadena === 'string' && cadena !== '')
}

export default FRASES
