// src/content/frases-v2/budismo.js
// Frases originales con referencias budistas (SPEC_29 §8.5).
//
// **Solo llegan a quien eligió Budismo.** Son redacción de Strivo, no citas:
// cuando dicen «la tradición enseña», resumen una enseñanza con palabras
// propias y no ponen nada en boca de nadie. Ninguna va entre comillas.
//
// **Solo se añade al final de cada lista.** El id sale de la posición.

import { originales } from './construir.js'

export default originales('budismo', {
  gratitud: [
    'La tradición budista invita a agradecer cada momento de atención.',
    'Agradecer el presente también es una forma de práctica.',
    'Cada respiración consciente es un regalo que puedes recibir.',
    'La gratitud nace de ver con claridad lo que hay.',
    'Puedes agradecer a tus maestros, a la sangha y al camino.',
    'Ver la interdependencia de todo despierta gratitud.',
    'Tu comida de hoy reúne el trabajo de muchos seres.',
    'La generosidad, central en el budismo, empieza por agradecer.',
    'Agradecer la impermanencia hace más valioso cada momento.',
    'La atención plena convierte lo cotidiano en motivo de gratitud.',
    'Hay gratitud en reconocer las causas que hicieron posible este día.',
    'Comer con atención es honrar todo lo que llegó a tu plato.',
    'Puedes agradecer las enseñanzas que te ayudan a ver con más claridad.',
    'La alegría compasiva celebra el bien de otros.',
    'La tradición budista invita a valorar esta vida humana como una oportunidad preciosa.',
    'Cada encuentro es una ocasión de practicar la bondad amorosa.',
    'Agradecer es dejar de dar por sentado lo que existe.',
    'La práctica de la gratitud suaviza el apego.',
    'Puedes dedicar el bien de este día a todos los seres.',
    'Un instante de presencia plena ya es un regalo.',
  ],
  calma: [
    'Puedes volver a la respiración como a un refugio.',
    'Los pensamientos aparecen y se van como nubes en el cielo.',
    'La atención plena empieza con notar este momento.',
    'El camino medio evita los extremos y abre espacio a la calma.',
    'Observar sin aferrarte trae serenidad.',
    'Puedes sentarte en silencio y simplemente estar.',
    'La mente se aclara como el agua cuando se deja reposar.',
    'Cada paso puede ser una meditación caminando.',
    'La ecuanimidad es una calma que acoge todo.',
    'Notar la respiración entrando y saliendo te devuelve al presente.',
    'Una campana o un silencio pueden marcar una pausa consciente.',
    'Puedes observar la inquietud sin convertirte en ella.',
    'La práctica budista enseña a soltar el apego a lo que agita.',
    'Hay serenidad en hacer cada cosa con plena atención.',
    'El presente es el lugar donde la calma puede practicarse.',
    'Puedes sonreír a tu respiración.',
    'La mente de principiante mira cada momento con frescura.',
    'Una meditación breve también es práctica.',
    'Las emociones intensas, observadas con calma, pierden fuerza.',
    'Puedes dejar que el sonido, la luz y el aire sean tu ancla.',
  ],
  identidad: [
    'Según el budismo, todo lo que somos está en cambio constante.',
    'Puedes soltar las etiquetas que te limitan.',
    'La tradición enseña que la naturaleza búdica está presente en cada ser.',
    'Tu práctica es tu camino, recorrido paso a paso.',
    'La compasión hacia ti también forma parte del camino.',
    'Puedes cultivar la recta intención en lo que haces hoy.',
    'Lo que piensas, dices y haces va dando forma a tu vida.',
    'El budismo invita a conocerte observando sin juzgar.',
    'Puedes mirar tu mente con curiosidad y ternura.',
    'La bondad amorosa empieza por desearte bien.',
    'No hay un yo fijo que defender; hay un camino que recorrer.',
    'Tus acciones intencionadas siembran semillas en tu vida.',
    'Tomar refugio en el Buda, el dharma y la sangha también es pertenecer.',
    'Puedes ser testigo amable de tus pensamientos.',
    'La sabiduría y la compasión crecen juntas.',
    'La recta palabra cuida a quien habla y a quien escucha.',
    'Cada día puedes despertar un poco más.',
    'Tu práctica no tiene por qué ser perfecta para ser sincera.',
    'Puedes reconocer tus patrones sin identificarte con ellos.',
    'Ser consciente de tus intenciones es parte del camino.',
  ],
  aceptacion: [
    'Todo lo condicionado es impermanente, también lo que hoy duele.',
    'La impermanencia invita a sostener las cosas con suavidad.',
    'Puedes aceptar el momento tal como es, sin añadirle sufrimiento.',
    'El apego a lo que imaginabas también puede soltarse.',
    'Las sensaciones surgen, permanecen un rato y se disuelven.',
    'Para el budismo, reconocer el sufrimiento es el primer paso del camino.',
    'Puedes acoger lo difícil con compasión.',
    'La ecuanimidad no es indiferencia; es equilibrio.',
    'Nada permanece igual, y en eso hay libertad.',
    'Soltar el resentimiento también es cuidarte.',
    'Lo que surge también se va.',
    'La compasión acepta a los demás con sus límites.',
    'Puedes mirar el cambio sin miedo.',
    'La práctica budista acompaña el dolor sin negarlo.',
    'Cada momento es nuevo, aunque se parezca al anterior.',
    'Aceptar es dejar de pelear con la realidad para verla mejor.',
    'Las hojas caen y el árbol sigue vivo.',
    'Puedes descansar en lo que es, aquí y ahora.',
    'Las condiciones cambian, y con ellas cambia la experiencia.',
    'El desapego no es frialdad; es amar sin aferrarse.',
  ],
  esfuerzo: [
    'El recto esfuerzo es amable y constante, no forzado.',
    'La práctica diaria, aunque sea breve, da frutos con el tiempo.',
    'Puedes volver a sentarte después de una pausa; el camino espera.',
    'El cultivo de la mente es paciente.',
    'Como la cuerda de un instrumento, el esfuerzo pide no estar ni muy tenso ni muy flojo.',
    'Cada acto de bondad fortalece el camino.',
    'Puedes practicar la atención en cualquier gesto cotidiano.',
    'La disciplina budista nace del cuidado, no del castigo.',
    'Un paso consciente a la vez también es práctica.',
    'El noble óctuple sendero se recorre en lo cotidiano.',
    'Puedes cultivar la generosidad con gestos pequeños.',
    'La diligencia amable sostiene la práctica.',
    'Volver a la atención cada vez que se pierde es la práctica misma.',
    'Sembrar intenciones sanas da frutos a su tiempo.',
    'La práctica no busca llegar rápido, sino ver con claridad.',
    'Puedes dedicar el esfuerzo de hoy al bien de otros.',
    'La paciencia es una de las perfecciones del camino.',
    'El trabajo hecho con atención también es meditación.',
    'Cultivar la compasión pide práctica, como cualquier arte.',
    'Cada día es una ocasión de practicar la recta acción.',
  ],
})
