// src/content/frases-v2/cristianismo.js
// Frases originales con referencias cristianas (SPEC_29 §8.5).
//
// **Solo llegan a quien eligió Cristianismo.** Son redacción de Strivo, no
// citas: no van entre comillas ni se atribuyen a nadie, aunque nombren a Dios,
// a Jesús o la oración. Invitan; no imponen doctrina, no prometen protección ni
// resultados y no juzgan las decisiones de nadie (§9).
//
// **Solo se añade al final de cada lista.** El id sale de la posición.

import { originales } from './construir.js'

export default originales('cristianismo', {
  gratitud: [
    'Hoy puedes dar gracias a Dios por algo pequeño.',
    'Cada día puede recibirse como un regalo de Dios.',
    'La gratitud es una forma sencilla de oración.',
    'Dar gracias a Dios también es mirar con más amor lo que tienes.',
    'El pan de cada día también merece una oración de gracias.',
    'Agradecer a Dios por las personas que amas une tu corazón al suyo.',
    'La fe se alimenta de reconocer los dones recibidos.',
    'Puedes empezar el día con un gracias a Dios en silencio.',
    'Hay huellas de la bondad de Dios en lo cotidiano.',
    'La gratitud cristiana mira lo recibido como don, no como derecho.',
    'Agradecer al Señor por este día también es confiar en él.',
    'Una oración de gracias puede ser muy breve.',
    'Dios se deja encontrar en las cosas sencillas.',
    'La comunidad de fe también es un motivo de gratitud.',
    'Dar gracias en lo pequeño prepara el corazón para lo grande.',
    'Cada persona que te ama refleja algo del amor de Dios.',
    'Puedes agradecer a Dios incluso lo que todavía no entiendes.',
    'La creación entera es una invitación a la alabanza.',
    'Agradecer es una manera de reconocer la gracia de Dios en tu vida.',
    'Jesús daba gracias antes de compartir el pan.',
  ],
  calma: [
    'Puedes poner en manos de Dios lo que hoy te inquieta.',
    'En la oración también hay descanso.',
    'Dios te espera en el silencio, sin prisa.',
    'Puedes confiar tus preocupaciones a Dios y respirar.',
    'La paz de Cristo puede acompañarte en medio del ruido.',
    'Un momento de oración puede ordenar tu día.',
    'Jesús invitaba a descansar a quienes llegaban con cansancio.',
    'La fe no quita las dificultades, pero puede darles otra luz.',
    'Puedes rezar con pocas palabras; Dios entiende el corazón.',
    'El silencio ante Dios también es oración.',
    'Hay calma en confiar a Dios el camino de hoy.',
    'Puedes dejar tus cargas al pie de la cruz.',
    'Una oración breve puede repetirse en cualquier momento del día.',
    'Dios no tiene prisa contigo.',
    'En la presencia de Dios puedes ser quien eres.',
    'Puedes empezar el día pidiendo paz para ti y para otros.',
    'La fe también es aprender a esperar con calma.',
    'Los salmos invitan a estar en quietud delante de Dios.',
    'Una vela encendida puede acompañar un momento de oración.',
    'La calma del Evangelio se aprende día a día.',
  ],
  identidad: [
    'El amor de Dios no depende de lo que logres hoy.',
    'Cada persona lleva la imagen de Dios, también tú.',
    'Para Dios tu nombre es importante.',
    'La fe te invita a mirarte con misericordia.',
    'Puedes vivir tu fe con sencillez y alegría.',
    'Amar al prójimo como a ti incluye también tratarte con amor.',
    'Tus dones también son una forma de servir.',
    'Dios conoce tu historia y no se cansa de ti.',
    'La humildad cristiana no es menospreciarte; es verte con verdad.',
    'Seguir a Jesús es aprender a amar en lo cotidiano.',
    'Tu vida puede ser un reflejo pequeño del amor de Dios.',
    'La fe crece en las preguntas tanto como en las certezas.',
    'Ser luz para otros empieza con gestos sencillos.',
    'Tu vocación se descubre poco a poco, escuchando.',
    'Dios te llama por tu nombre, con paciencia.',
    'Puedes ser fiel en lo pequeño.',
    'La misericordia que recibes también puedes ofrecerla.',
    'Tu fe es un camino personal dentro de una comunidad.',
    'La oración también es un espacio para conocerte.',
    'Eres parte de una historia de fe que viene de lejos.',
  ],
  aceptacion: [
    'Puedes entregar a Dios lo que no está en tus manos.',
    'Aceptar la voluntad de Dios no significa dejar de sentir.',
    'Dios acompaña también los días difíciles.',
    'La cruz recuerda que el dolor no tiene la última palabra.',
    'Puedes llorar delante de Dios sin vergüenza.',
    'El perdón de Dios es más grande que tus errores.',
    'Perdonar es un camino que se recorre con tiempo.',
    'Puedes pedir la gracia de aceptar lo que no puedes cambiar.',
    'La fe convive con las dudas.',
    'En la debilidad también puede manifestarse la fuerza de Dios.',
    'Aceptar tus límites también es reconocer que no eres Dios.',
    'Puedes dejar el pasado en manos de la misericordia de Dios.',
    'Hay esperanza cristiana incluso en lo que termina.',
    'Los tiempos de Dios suelen ser distintos de los nuestros.',
    'Puedes confiar a Dios tu historia, con lo que tiene de difícil.',
    'Jesús también conoció el cansancio y la tristeza.',
    'Orar puede ser contarle a Dios cómo estás.',
    'Aceptar a los demás es una forma de amarlos como Cristo.',
    'La paciencia es un fruto que se cultiva con fe.',
    'Puedes vivir este día con fe, paso a paso y sin prisa.',
  ],
  esfuerzo: [
    'Puedes ofrecer a Dios el trabajo de hoy.',
    'Servir a otros es una forma de seguir a Jesús.',
    'Lo que haces con amor tiene valor a los ojos de Dios.',
    'La fe se hace concreta en las obras sencillas.',
    'Puedes poner tus talentos al servicio de los demás.',
    'Cada día es una nueva oportunidad para amar mejor.',
    'La caridad se practica en lo pequeño.',
    'Volver a empezar es parte del camino de la fe.',
    'Puedes pedir fuerza para lo que hoy te toca.',
    'La perseverancia en la oración se construye con días sencillos.',
    'Trabajar con honestidad también es una forma de alabar a Dios.',
    'Un acto de bondad puede ser tu oración de hoy.',
    'La fidelidad se muestra en lo cotidiano.',
    'Puedes hacer tu parte y dejar el resto en manos de Dios.',
    'La esperanza cristiana anima a seguir sembrando.',
    'Ayudar a quien lo necesita es encontrarse con Cristo.',
    'El amor al prójimo se muestra con gestos concretos.',
    'Hacer el bien a tu ritmo también es fidelidad.',
    'Tu trabajo de hoy puede ser una ofrenda.',
    'La comunidad de fe ayuda a sostener el esfuerzo.',
  ],
})
