// src/content/frases-v2/espiritual.js
// Frases espirituales sin una tradición específica (SPEC_29 §8.5).
//
// Para quien eligió «Espirituales, sin una tradición específica». Hablan del
// interior, del silencio, de lo sagrado y de lo que trasciende, y **no
// presuponen una doctrina**: no nombran a Dios ni a ninguna figura, texto o
// práctica propia de una tradición. `scripts/validar-frases.js` lo vigila.
//
// **Solo se añade al final de cada lista.** El id sale de la posición.

import { originales } from './construir.js'

export default originales('espiritual_general', {
  gratitud: [
    'Dar gracias por la vida también es una forma de recogimiento.',
    'Hay algo sagrado en lo cotidiano cuando lo miras con gratitud.',
    'Agradecer conecta tu interior con algo más grande.',
    'El regalo de este día merece un momento de reverencia.',
    'La gratitud abre el corazón a lo que trasciende.',
    'Cada amanecer puede recibirse como un don.',
    'Hay una bendición escondida en lo sencillo.',
    'Agradecer es reconocer la vida que fluye a través de ti.',
    'El alma se ensancha cuando agradece.',
    'La gratitud es un puente entre tu espíritu y el mundo.',
    'Puedes agradecer al misterio que te trajo hasta aquí.',
    'Lo que recibes con gratitud se vuelve sagrado.',
    'El corazón agradecido encuentra luz en lugares inesperados.',
    'Dar gracias también es una manera de sentirte en comunión con todo.',
    'La vida es un don que se renueva cada mañana.',
    'Hay algo de gracia en los encuentros que no buscaste.',
    'Agradecer en silencio también es una plegaria.',
    'Tu espíritu se alimenta de lo que agradeces.',
    'Hay algo luminoso en reconocer lo recibido.',
    'La gratitud te recuerda que formas parte de algo mayor.',
  ],
  calma: [
    'El silencio interior es un lugar al que puedes volver.',
    'Tu espíritu conoce el camino hacia la calma.',
    'En lo profundo de ti hay una quietud que no se agita.',
    'La paz interior se cultiva como un jardín sagrado.',
    'Puedes respirar y dejar que el alma se asiente.',
    'El silencio también tiene algo que decirte.',
    'Hay una calma más honda que cualquier preocupación.',
    'Tu interior puede ser un santuario.',
    'La quietud abre espacio a lo que trasciende.',
    'Puedes descansar en el presente como en un lugar sagrado.',
    'La serenidad del espíritu no depende del ruido de fuera.',
    'Escuchar tu interior también es volver a casa.',
    'Hay paz en confiar en el misterio de la vida.',
    'Tu alma pide espacios de silencio para hablar.',
    'La calma es una forma de presencia espiritual.',
    'Cada respiración consciente puede ser un pequeño ritual.',
    'El corazón en calma ve con más claridad.',
    'Puedes dejar tus preocupaciones a un lado y abrirte a lo sagrado.',
    'Hay luz en tu interior aunque el día esté nublado.',
    'La paz más profunda nace desde adentro.',
  ],
  identidad: [
    'Hay en ti una dimensión profunda que merece atención.',
    'Tu alma tiene un ritmo propio.',
    'En tu interior hay una luz que te pertenece.',
    'Tu camino espiritual es tuyo y se recorre a tu manera.',
    'Puedes buscar sentido sin tener todas las respuestas.',
    'Tu valor es más profundo que cualquier logro.',
    'Conocerte también es una búsqueda espiritual.',
    'Hay algo sagrado en tu manera de estar en el mundo.',
    'Tu esencia permanece aunque cambien las circunstancias.',
    'El corazón sabe cosas que la mente tarda en entender.',
    'Tu búsqueda interior es una forma de honrar la vida.',
    'Eres parte de un tejido más grande que tu historia personal.',
    'Tu intuición también es una forma de sabiduría.',
    'Cada persona lleva dentro un misterio digno de respeto.',
    'Tu espíritu se fortalece cuando eres fiel a lo que amas.',
    'El sentido de tu vida puede revelarse poco a poco.',
    'Escuchar tu voz interior es honrar quién eres.',
    'Hay una parte de ti que permanece en calma.',
    'Tu vida es una expresión única de algo más grande.',
    'Buscar lo sagrado también es buscarte.',
  ],
  aceptacion: [
    'Puedes entregar lo que no controlas y quedarte en paz.',
    'Confiar en el curso de la vida también es descansar.',
    'Lo que llega puede recibirse con el corazón abierto.',
    'Hay sabiduría en aceptar los ciclos de la vida.',
    'El alma también aprende de los días difíciles.',
    'Puedes soltar con amor lo que ya cumplió su tiempo.',
    'Aceptar puede ser abrirte a algo más grande, sin perderte.',
    'Todo lo que vive cambia, y en el cambio también hay sentido.',
    'Puedes abrazar el misterio sin necesidad de explicarlo.',
    'La paz llega cuando dejas de luchar con lo que es.',
    'Hay un orden más amplio que a veces no alcanzamos a ver.',
    'Puedes acoger tus emociones como visitantes de paso.',
    'El dolor también puede volverse un camino de comprensión.',
    'Aceptar es abrir las manos para recibir lo que viene.',
    'La vida tiene sus tiempos, y confiar en ellos trae calma.',
    'Lo que se va deja espacio para lo nuevo.',
    'Puedes descansar en la confianza de que no todo depende de ti.',
    'La compasión empieza por aceptarte.',
    'El espíritu encuentra paz cuando deja de resistirse.',
    'Hay belleza en lo transitorio.',
  ],
  esfuerzo: [
    'Tu práctica interior crece con pequeños gestos diarios.',
    'Cultivar el espíritu también pide constancia y ternura.',
    'Cada día es una nueva oportunidad para vivir desde el corazón.',
    'El servicio a los demás es un camino espiritual.',
    'Lo que haces con amor tiene un valor que trasciende.',
    'La perseverancia en lo esencial nutre el alma.',
    'Un acto de bondad puede ser tu ofrenda de hoy.',
    'El camino interior se recorre un paso a la vez.',
    'Tu dedicación puede ser una forma de devoción.',
    'Volver a tu práctica después de una pausa también es fidelidad.',
    'Trabajar con presencia convierte lo cotidiano en algo sagrado.',
    'La disciplina amable es una forma de cuidar tu espíritu.',
    'Lo que se ofrece con sinceridad tiene algo de sagrado.',
    'Puedes poner intención en lo que haces hoy.',
    'El crecimiento interior no tiene prisa.',
    'Lo que siembras en tu interior florece a su tiempo.',
    'Dar lo mejor de ti puede ser un acto espiritual.',
    'La constancia en el bien transforma poco a poco.',
    'Hacer las cosas con el corazón también es una práctica.',
    'Tu esfuerzo puede ser una forma de gratitud a la vida.',
  ],
})
