// src/content/frases-v2/estoicismo.js
// Frases originales con referencias estoicas (SPEC_28 §8.5).
//
// **Solo llegan a quien eligió Estoicismo.** Son redacción de Strivo, no
// citas: resumen ideas de la escuela con palabras propias y no ponen nada en
// boca de Marco Aurelio, Epicteto ni Séneca. Ninguna va entre comillas.
//
// Dos de ellas no son aptas con ánimo bajo: imaginar lo que podría salir mal
// y la muerte como parte del orden natural son ejercicios de la escuela, pero
// no son lo que se le abre a alguien que lleva tres noches de cansancio.
//
// **Solo se añade al final de cada lista.** El id sale de la posición.

import { originales } from './construir.js'

export default originales(
  'estoicismo',
  {
    gratitud: [
      'Los estoicos agradecían lo que tenían recordando que era prestado.',
      'Puedes agradecer lo que hoy está, sabiendo que todo cambia.',
      'Recordar a quienes te enseñaron algo bueno es una práctica estoica.',
      'La gratitud estoica valora lo que depende de ti.',
      'Disfrutar sin aferrarte es una forma de agradecer.',
      'Cada día puede recibirse como un regalo que no estaba garantizado.',
      'Los filósofos estoicos agradecían por escrito a sus maestros y familiares.',
      'Agradecer lo suficiente es una forma de libertad.',
      'La razón y la virtud son bienes que puedes agradecer y cultivar.',
      'Puedes valorar a las personas cercanas mientras están contigo.',
      'El estoicismo invita a apreciar lo que tienes como si pudieras perderlo.',
      'La naturaleza ofrece lo necesario a quien sabe mirar.',
      'Agradecer también es reconocer que formas parte de un todo.',
      'Lo sencillo bien apreciado basta para una vida serena.',
      'Puedes agradecer las dificultades que te enseñaron algo.',
      'La gratitud estoica no depende de que todo salga bien.',
      'Cada mañana es una nueva ocasión de vivir según la virtud.',
      'Apreciar el presente es una lección central del estoicismo.',
      'Puedes agradecer la oportunidad de actuar bien hoy.',
      'La amistad era, para los estoicos, uno de los bienes más valiosos.',
    ],
    calma: [
      'Distinguir lo que depende de ti de lo que no trae mucha calma.',
      'Muchas veces inquieta más el juicio sobre las cosas que las cosas mismas.',
      'Puedes revisar tus impresiones antes de darles la razón.',
      'La tradición estoica propone volver a tu ciudadela interior.',
      'Antes de reaccionar, puedes preguntarte si eso está en tu poder.',
      'El futuro aún no llega; el presente es donde puedes actuar.',
      'La serenidad estoica nace de aceptar lo que no controlas.',
      'Puedes observar la ira y darle tiempo antes de actuar.',
      'Imaginar con calma lo que podría salir mal prepara el ánimo.',
      'La mente ordenada es un refugio que llevas contigo.',
      'Lo que pasa fuera puede tocarte sin gobernarte.',
      'La razón puede ser una buena compañera en momentos agitados.',
      'Puedes caminar despacio y pensar con claridad, como los antiguos filósofos.',
      'El estoicismo enseña que la paz está en tu manera de responder.',
      'Una pausa antes de juzgar ahorra muchas inquietudes.',
      'Puedes mirar el día desde lo alto, como quien ve una ciudad desde una colina.',
      'La calma estoica no es frialdad; es claridad.',
      'Lo que no depende de ti puede dejar de ocupar tu mente.',
      'Puedes escribir tus pensamientos al final del día, como hacían los estoicos.',
      'El presente es breve y suficiente para vivir bien.',
    ],
    identidad: [
      'Para los estoicos, la virtud es el bien verdadero.',
      'Tu carácter se forma en lo que eliges cada día.',
      'Puedes practicar justicia, templanza, valentía y sabiduría en lo pequeño.',
      'Lo que eres no depende de la opinión ajena.',
      'El estoicismo invita a la coherencia entre lo que piensas y lo que haces.',
      'Puedes interpretar con dignidad el papel que te toca.',
      'Vivir según la naturaleza es vivir según la razón y la bondad.',
      'Formas parte de la comunidad humana, una ciudad común.',
      'Puedes repasar tu día por la noche, como proponía la tradición estoica.',
      'Tu libertad interior empieza en cómo juzgas lo que pasa.',
      'La sabiduría práctica se ejercita en decisiones sencillas.',
      'Tus principios pueden guiarte sin necesidad de aplausos.',
      'Ser una buena persona vale más que hablar de cómo serlo.',
      'Lo que depende de ti es tu intención, tu juicio y tu acción.',
      'Puedes cultivar la templanza en lo que comes, dices y haces.',
      'La valentía estoica también es decir la verdad con amabilidad.',
      'Cada persona tiene un papel propio en el orden del mundo.',
      'Tu razón es una chispa que puedes cuidar.',
      'El estoicismo valora más el carácter que las circunstancias.',
      'Puedes practicar hoy un poco más de justicia y de bondad.',
    ],
    aceptacion: [
      'Aceptar lo que sucede es el inicio de la serenidad estoica.',
      'Amor fati: abrazar lo que te toca vivir, también lo difícil.',
      'Lo que no depende de ti puede recibirse con calma.',
      'Todo cambia, y la naturaleza sigue su curso.',
      'Puedes querer lo que ocurre en lugar de luchar contra ello.',
      'Los obstáculos también pueden convertirse en camino.',
      'Para los estoicos, la muerte y el cambio forman parte del orden natural.',
      'Las opiniones de otros no están en tu poder.',
      'Puedes aceptar tus límites y obrar dentro de ellos.',
      'Lo que se pierde vuelve a la naturaleza de donde vino.',
      'El estoicismo invita a sostener todo con ligereza.',
      'Puedes aceptar el día sin exigirle que sea distinto.',
      'Las circunstancias no te definen; tu respuesta sí.',
      'Lo pasado ya no está en tu poder; el presente, un poco.',
      'Recordar que todo es pasajero da proporción a las preocupaciones.',
      'Los estoicos veían en cada dificultad una ocasión de ejercitar la virtud.',
      'Puedes aceptar a los demás sabiendo que actúan según lo que entienden.',
      'La serenidad está en querer lo que es, no lo que imaginabas.',
      'Lo que hoy molesta será pequeño mirado desde lejos.',
      'Puedes hacer lo que te toca y aceptar el resto.',
    ],
    esfuerzo: [
      'Cada mañana los estoicos se preparaban para actuar bien.',
      'La virtud se ejercita como un oficio, con práctica diaria.',
      'Puedes hacer lo que te corresponde con atención y sin prisa.',
      'El esfuerzo estoico se pone en lo que depende de ti.',
      'Los ejercicios del estoicismo eran breves y diarios.',
      'Puedes corregir el rumbo sin culparte.',
      'La perseverancia es una forma de templanza.',
      'Cada dificultad es una ocasión de practicar la paciencia.',
      'Puedes obrar por el bien común como parte de tu naturaleza.',
      'La disciplina estoica se apoya en la razón, no en el castigo.',
      'Hacer bien tu parte ya es suficiente.',
      'Puedes empezar cada mañana tu oficio de persona con calma.',
      'La práctica de la virtud no tiene prisa.',
      'Importa el esfuerzo bien dirigido, no el aplauso.',
      'Puedes ejercitar el carácter en las pequeñas incomodidades.',
      'Aprender de los sabios es parte del camino estoico.',
      'La constancia en lo que depende de ti trae serenidad.',
      'Puedes comenzar de nuevo cada día, como proponían los estoicos.',
      'El esfuerzo justo es el que sirve a la virtud.',
      'Cada decisión bien pensada fortalece tu ciudadela interior.',
    ],
  },
  { noAptas: ['F2-EST-CAL-009', 'F2-EST-ACE-007'] },
)
