// src/content/frases-v2/hinduismo.js
// Frases originales con referencias hindúes (SPEC_29 §8.5).
//
// **Solo llegan a quien eligió Hinduismo.** Son redacción de Strivo, no
// citas: algunas recogen imágenes de la tradición —la llama quieta, el fruto
// de la acción— con palabras propias y sin atribuirlas a ningún texto. Por eso
// ninguna va entre comillas.
//
// **Solo se añade al final de cada lista.** El id sale de la posición.

import { originales } from './construir.js'

export default originales('hinduismo', {
  gratitud: [
    'Agradecer cada día también puede ser una ofrenda.',
    'La tradición hindú invita a ver lo divino en todo lo que existe.',
    'Namasté honra lo sagrado que hay en la otra persona.',
    'Puedes ofrecer tu gratitud como quien ofrece una flor.',
    'El alimento recibido con gratitud se vuelve prasad, un regalo sagrado.',
    'Agradecer a quien te enseña es parte de la tradición del gurú.',
    'La devoción, bhakti, empieza muchas veces por dar gracias.',
    'La tierra, el agua y el fuego también reciben gratitud en la tradición hindú.',
    'Cada amanecer puede saludarse con reverencia.',
    'Agradecer es reconocer lo divino que te sostiene.',
    'Una lámpara encendida puede ser un gesto de gratitud.',
    'La gratitud abre el corazón al amor devocional.',
    'Puedes agradecer el dharma que orienta tus días.',
    'Todo lo que recibes puede volver al mundo como ofrenda.',
    'El canto y la oración son formas antiguas de agradecer.',
    'Agradecer la vida también es honrar el Ser que habita en ti.',
    'La hospitalidad sagrada empieza por agradecer a quien llega.',
    'Hay gratitud en reconocer la armonía de la creación.',
    'Puedes dedicar este día a lo divino con un gesto sencillo.',
    'La alegría de la devoción nace de un corazón agradecido.',
  ],
  calma: [
    'El Atman, el Ser interior, permanece sereno bajo el movimiento de la mente.',
    'Puedes repetir un mantra en silencio para volver a la calma.',
    'La práctica del yoga une respiración, cuerpo y atención.',
    'En la quietud puedes encontrar al Ser que observa.',
    'El pranayama enseña que la respiración puede guiar la calma.',
    'La mente puede aquietarse como una llama donde no hay viento.',
    'Puedes descansar en el silencio entre dos pensamientos.',
    'Om puede ser un sonido para volver a tu centro.',
    'La ecuanimidad recibe con serenidad lo agradable y lo difícil.',
    'Hay paz en dedicar el día a lo divino.',
    'El yoga es también el arte de calmar la mente.',
    'Puedes encender una lámpara y quedarte un momento en silencio.',
    'La devoción serena el corazón inquieto.',
    'Lo eterno en ti no se agita con los cambios del día.',
    'Meditar es volver una y otra vez al centro.',
    'Puedes sentarte, respirar y recordar que eres más que tus pensamientos.',
    'La tradición hindú enseña que la calma es la naturaleza del Ser.',
    'Un canto suave puede ordenar la mente.',
    'La práctica espiritual hindú valora la quietud interior.',
    'En el silencio, lo divino también se hace presente.',
  ],
  identidad: [
    'Según la tradición hindú, el Ser que habita en ti es eterno.',
    'Tu dharma es tu manera propia de vivir con rectitud.',
    'Puedes seguir tu camino aunque sea distinto del de otros.',
    'Hay algo divino en ti que merece respeto.',
    'Tus acciones expresan quién eres cuando las haces con sinceridad.',
    'La tradición hindú enseña que todos los seres comparten una misma esencia.',
    'Tu camino espiritual puede ser de conocimiento, de devoción o de acción.',
    'La tradición dice que eres más que tu cuerpo y que tus pensamientos.',
    'Vivir tu dharma vale más que imitar el de otros.',
    'La sabiduría, jñana, empieza por conocerte.',
    'Tu práctica es una forma de honrar lo divino en ti.',
    'Puedes ofrecer tus talentos como servicio, seva.',
    'El Ser no se define por lo que ganas o pierdes.',
    'Tu vida es parte del gran tejido de la creación.',
    'Hay luz en ti, como en cada ser.',
    'La humildad y la devoción crecen juntas.',
    'Conocer tu dharma es escuchar con calma.',
    'Puedes vivir con integridad en lo pequeño.',
    'Lo divino se manifiesta de muchas formas, también en tu vida.',
    'Tu esencia es paz, aunque el día esté agitado.',
  ],
  aceptacion: [
    'Puedes hacer tu parte y soltar el fruto de la acción.',
    'Los ciclos de la vida, según la tradición hindú, se renuevan sin fin.',
    'La ecuanimidad recibe con igual calma el éxito y la dificultad.',
    'Cambian el cuerpo y las circunstancias; el Ser permanece.',
    'Puedes ofrecer a lo divino lo que no entiendes.',
    'Aceptar tu dharma es aceptar tu lugar en el mundo.',
    'Todo lo que nace cambia, y eso forma parte del orden de la vida.',
    'La entrega, en la tradición devocional, trae paz.',
    'Puedes recibir lo que llega como parte de tu camino.',
    'Soltar el apego al resultado libera el corazón.',
    'El placer y el dolor vienen y van, como las estaciones.',
    'Puedes confiar tus preocupaciones a lo divino.',
    'La paciencia es una virtud apreciada en la tradición hindú.',
    'Hay sabiduría en aceptar los tiempos de la vida.',
    'Lo que hoy pesa también es parte del viaje del alma.',
    'Puedes mirar los cambios con serenidad, como testigo.',
    'Aceptar a otros es reconocer lo divino en ellos.',
    'La vida tiene un ritmo que no depende de tu prisa.',
    'Puedes entregar el día terminado con gratitud y sin juicio.',
    'El río sigue su curso hasta el mar, sin luchar contra él.',
  ],
  esfuerzo: [
    'Puedes actuar con dedicación sin apegarte al resultado.',
    'El karma yoga convierte el trabajo en ofrenda.',
    'Hacer tu parte con el corazón también es una práctica espiritual.',
    'El servicio desinteresado, seva, es un camino de crecimiento.',
    'La disciplina, tapas, puede vivirse con amor.',
    'Cada acción hecha como ofrenda tiene un valor sagrado.',
    'Puedes practicar yoga como un diálogo amable con tu cuerpo.',
    'La constancia en la práctica fortalece el espíritu.',
    'La acción consciente es una forma de yoga.',
    'Cumplir tu dharma con sencillez ya es valioso.',
    'Puedes dedicar el esfuerzo de hoy a lo divino.',
    'La devoción también se expresa en el cuidado de las cosas.',
    'Lo que haces con amor no se pierde.',
    'La práctica espiritual se sostiene con paciencia.',
    'Cada día es una oportunidad de actuar con rectitud.',
    'Puedes trabajar con serenidad y dejar el fruto en manos de lo divino.',
    'El esfuerzo sincero purifica la intención.',
    'Repetir el nombre divino con constancia puede acompañar tu día.',
    'El estudio de los textos sagrados también es una práctica.',
    'Hacer el bien sin esperar recompensa es una forma de libertad.',
  ],
})
