// src/content/frases-v2/secular.js
// Frases seculares: para quien prefiere frases seculares y para quien todavía
// no decidió (SPEC_29 §8.5).
//
// Hablan desde lo humano y lo natural —el cuerpo, la comunidad, el
// conocimiento, la naturaleza— y **no contienen referencias religiosas ni
// espirituales explícitas**. No compiten con lo universal: le dan a este
// perfil una voz propia.
//
// **Solo se añade al final de cada lista.** El id sale de la posición.

import { originales } from './construir.js'

export default originales('secular', {
  gratitud: [
    'Muchas personas que no conoces hicieron posible tu mañana.',
    'La ciencia, el arte y el cuidado de otros llegan a tu vida cada día.',
    'El conocimiento que usas hoy lo construyeron generaciones enteras.',
    'Formas parte de una red de ayuda que rara vez se ve completa.',
    'Una médica, un maestro, una vecina: la vida en común sostiene la tuya.',
    'Agradecer a personas concretas es una forma de cuidar la comunidad.',
    'La tierra, el agua y el clima hacen posible lo que comes hoy.',
    'Cada libro que leíste es la conversación de alguien con el mundo.',
    'La gratitud entre personas fortalece los lazos que nos sostienen.',
    'Detrás de cada cosa útil hay ingenio humano y paciencia.',
    'La vida en este planeta es una coincidencia asombrosa que merece aprecio.',
    'Las bibliotecas, los parques y los hospitales son regalos de la vida en común.',
    'Puedes agradecer a la persona concreta que te ayudó.',
    'La curiosidad de otros abrió caminos que hoy recorres sin pensar.',
    'Agradecer es reconocer que cada vida se construye con muchas manos.',
    'La música que te acompaña nació del trabajo de alguien.',
    'El cuerpo trabaja en silencio para que hoy puedas estar aquí.',
    'La comunidad que te rodea también es un bien que se cuida.',
    'Cada idea que te ayuda tuvo antes a alguien que la pensó.',
    'La luz del sol tardó ocho minutos en llegar hasta tu ventana.',
  ],
  calma: [
    'La respiración lenta le avisa al cuerpo que puede bajar el ritmo.',
    'Caminar al aire libre ayuda a que la mente se despeje.',
    'El cerebro también aprovecha las pausas para ordenar lo vivido.',
    'Mirar el horizonte relaja la vista y, con ella, el pensamiento.',
    'Dormir bien es una forma concreta de cuidarte.',
    'La naturaleza tiene ritmos lentos que pueden ayudarte a encontrar el tuyo.',
    'Un cielo estrellado pone en su escala las preocupaciones del día.',
    'El cuerpo se calma cuando la exhalación es más larga que la inhalación.',
    'Pensar con calma es pensar con más claridad.',
    'Un problema bien planteado ya es un problema más pequeño.',
    'La información y la paciencia suelen aclarar lo que el miedo agranda.',
    'La mente se aquieta cuando las manos hacen algo sencillo.',
    'Escribir lo que piensas puede ordenar lo que sientes.',
    'El universo lleva miles de millones de años sin prisa.',
    'La luz del atardecer avisa al cuerpo que se acerca el descanso.',
    'Un árbol tarda décadas en crecer y no parece apurado.',
    'Las emociones intensas suelen bajar si les das unos minutos.',
    'La calma también se cuida con lo básico: agua, comida y descanso.',
    'Separar los hechos de las suposiciones trae mucha tranquilidad.',
    'El sonido del agua corriente tiene algo que serena.',
  ],
  identidad: [
    'Tus valores pueden nacer de la reflexión y la experiencia.',
    'Lo que piensas por tu cuenta merece tu confianza.',
    'Tu curiosidad es una herramienta para entender el mundo.',
    'Ser parte de la humanidad es compartir dudas y descubrimientos.',
    'Tus convicciones pueden cambiar cuando aprendes algo nuevo.',
    'Pensar con libertad también es una forma de cuidarte.',
    'La ética se demuestra en cómo tratas a quienes te rodean.',
    'Puedes construir sentido a partir de lo que valoras.',
    'Tus preguntas son el inicio de cualquier descubrimiento.',
    'La razón y la ternura pueden convivir en una misma persona.',
    'Tu manera de razonar es tuya y vale la pena cuidarla.',
    'Somos lo que aprendemos y lo que compartimos.',
    'Tu historia forma parte de una historia humana mucho más grande.',
    'Puedes elegir tus principios con conocimiento y con calma.',
    'Lo que haces por los demás da sentido a tus días.',
    ['La empatía es una capacidad humana que se ejercita.', 'empatia'],
    'Tus decisiones éticas no necesitan testigos para valer.',
    'Eres una mezcla única de experiencia, memoria y elección.',
    'Dudar con honestidad es parte de pensar bien.',
    'Tu vida tiene el sentido que le das con tus actos.',
  ],
  aceptacion: [
    'Todo en la naturaleza cambia, y tú formas parte de ella.',
    'Las emociones son respuestas humanas, no defectos.',
    'La incertidumbre es parte de cómo funciona el mundo.',
    'Aceptar los hechos es el primer paso para decidir bien.',
    'El azar también juega su papel, y no todo es responsabilidad tuya.',
    'Los ciclos de la naturaleza enseñan que todo tiene su estación.',
    'Equivocarse es parte de aprender, también para la ciencia.',
    'No saber algo es el punto de partida de cualquier descubrimiento.',
    'El cuerpo tiene límites, y escucharlos es sensato.',
    'Las estrellas también nacen, cambian y se apagan.',
    'La vida es breve, y eso le da valor a cada día.',
    'No hace falta encontrar una razón para todo lo que pasa.',
    'Algunas preguntas siguen abiertas, y convivir con ellas es parte de pensar.',
    'Las personas cambian, y eso también es natural.',
    'La pérdida duele porque el vínculo era real.',
    'La realidad no está obligada a parecerse a lo que imaginamos.',
    'Puedes aceptar tus emociones como aceptas el clima.',
    'Las mareas suben y bajan sin pedir explicaciones.',
    'Nadie lo sabe todo, y esa es una buena noticia para aprender.',
    'Somos seres en cambio constante, por dentro y por fuera.',
  ],
  esfuerzo: [
    'Los grandes descubrimientos se hicieron con miles de intentos.',
    'Se aprende mejor practicando con pausas que con prisa.',
    'La paciencia de quienes investigan también es una forma de esfuerzo.',
    'Cada habilidad que admiras se aprendió practicando.',
    'Construir algo junto a otros hace más llevadero el esfuerzo.',
    'El descanso es parte del aprendizaje, no su enemigo.',
    'Probar, observar y ajustar también funciona en la vida diaria.',
    'Lo que se entiende a fondo cuesta más, y dura más.',
    'Las ideas maduran cuando se trabajan con calma.',
    'Un experimento que no sale también da información valiosa.',
    'Los puentes se construyen pieza por pieza.',
    'La curiosidad sostiene el esfuerzo mejor que la presión.',
    'Lo que aprendes de un intento te sirve para el siguiente.',
    'El conocimiento humano avanzó con paciencia, no con prisa.',
    'Practicar un poco cada día cambia la forma en que el cuerpo aprende.',
    'El trabajo en equipo multiplica lo que una persona puede hacer.',
    'Cada oficio guarda siglos de práctica acumulada.',
    'Puedes aprender algo útil de cada error.',
    'La constancia también es una forma de inteligencia.',
    'Las cosas bien hechas suelen tener detrás muchas versiones previas.',
  ],
})
