// src/content/frases-v2/universal.js
// Frases universales: las puede leer cualquier persona, haya elegido lo que
// haya elegido (SPEC_29 §8.5).
//
// **Universal quiere decir neutral, no «para todos los gustos».** Ninguna de
// estas frases nombra una tradición, una práctica religiosa, un concepto
// espiritual ni una escuela filosófica concreta: no son un atajo para enseñarle
// a alguien una referencia que no eligió. `scripts/validar-frases.js` lo vigila
// con una lista de marcas.
//
// Reglas de redacción (§10): una idea por frase, español de hoy, sin
// absolutos, sin mandatos, sin exclamaciones y sin léxico de rendimiento; sin
// marca de género en el trato a quien lee. La lista exacta vive en
// `validacion.js` (`LEXICO_PROHIBIDO`).
//
// **Solo se añade al final de cada lista.** El id sale de la posición
// (`construir.js`).

import { originales } from './construir.js'

export default originales('universal', {
  gratitud: [
    'Hoy puede haber algo pequeño que valga la pena agradecer.',
    'Agradecer no cambia lo que pasó; cambia la forma de mirarlo.',
    'Una taza caliente, una voz conocida, un rato de luz: también cuentan.',
    'Lo cotidiano sostiene más de lo que parece.',
    'Mirar lo que sí está es una manera tranquila de empezar.',
    'Quizá hoy alguien hizo algo por ti sin que lo pidieras.',
    ['Hay días en que agradecer es notar que respiras.', 'presencia'],
    'El agradecimiento crece cuando se le presta atención.',
    'Lo que se agradece se mira con más cuidado.',
    ['Un gesto amable recibido puede acompañarte todo el día.', 'amabilidad'],
    'Agradecer también es reconocer a quienes te sostienen.',
    'A veces lo valioso llega sin hacer ruido.',
    'Puedes agradecer algo sin que todo esté resuelto.',
    'La gratitud cabe incluso en un día complicado.',
    'Lo que hoy parece normal alguna vez fue un deseo.',
    'Una conversación sincera es un regalo discreto.',
    'Agradecer el descanso también es agradecer.',
    'El cuerpo que te trajo hasta aquí merece un gesto de aprecio.',
    'Hay belleza en lo que se repite cada mañana.',
    ['Notar la luz de la tarde puede ser suficiente por hoy.', 'presencia'],
    ['Quien te escucha de verdad te regala su tiempo.', 'empatia'],
    'Lo que tienes cerca a veces es lo más fácil de pasar por alto.',
    'Agradecer abre espacio para recibir con calma.',
    'Una comida compartida guarda más de lo que se ve en el plato.',
    'El agradecimiento no pide grandes motivos.',
    'Puedes dar gracias por lo aprendido, aunque haya costado.',
    'Cada día trae algo que no tuviste que pedir.',
    'La gratitud se nota más cuando se dice en voz alta.',
    'Recordar un buen momento también es volver a vivirlo un poco.',
    ['Hoy puedes agradecer a alguien con una palabra sencilla.', 'amabilidad'],
    'Lo que te hizo sonreír esta semana sigue contando.',
    'Agradecer es una forma de quedarte un momento con lo bueno.',
    'Un lugar donde te sientes en casa es una riqueza discreta.',
    'El agua, el pan y el techo merecen una mirada agradecida.',
    'Lo pequeño, bien mirado, deja de ser pequeño.',
    'Agradecer la ayuda recibida también te une a otras personas.',
    'La gratitud no niega lo difícil; lo acompaña.',
    'Hay personas que hacen tu día más ligero sin saberlo.',
    ['Un saludo cálido puede cambiar el tono de una mañana.', 'amabilidad'],
    ['Puedes agradecer la oportunidad de empezar de nuevo hoy.', 'esperanza_serena'],
    'Lo que funciona en tu vida también merece atención.',
    'Agradecer es mirar con ojos un poco más abiertos.',
    'Cada cosa buena de hoy tuvo detrás el trabajo de alguien.',
    'Hay gratitud en cuidar lo que ya tienes.',
    'Un rato de silencio también es algo que agradecer.',
    'La amistad se fortalece cuando se agradece.',
    'Lo que aprendiste de alguien sigue contigo.',
    ['Agradecer te devuelve al lugar donde estás.', 'presencia'],
    'Hoy quizá baste con reconocer una cosa buena.',
    'La naturaleza ofrece sin pedir nada a cambio.',
    'Un libro, una canción o una película pueden ser compañía valiosa.',
    'Decir gracias a tiempo deja menos palabras guardadas.',
    'Las manos que preparan algo para otros merecen reconocimiento.',
    'Hay alegría en recordar quién ha estado a tu lado.',
    'Lo que se recibe sin esperarlo tiene un sabor distinto.',
    'Agradecer también es una forma de memoria.',
    'A veces el mejor regalo del día es una pausa.',
    'Puedes agradecer lo que tu propio esfuerzo hizo posible.',
    'Un abrazo dice gracias sin necesidad de palabras.',
    'La gratitud hace más amplio lo que ya está aquí.',
    'Hoy hay algo que te sostiene, aunque no lo veas a primera vista.',
    'El sol de la mañana no pide nada por calentar.',
    'Las risas compartidas siguen sonando un rato después.',
    'Agradecer es reconocer que nadie hace su camino sin ayuda.',
    'Un mensaje inesperado puede ser motivo de gratitud.',
    'Quien te enseñó algo con paciencia sigue presente en lo que haces.',
    ['Lo bueno de hoy no tiene por qué ser extraordinario.', 'optimismo_realista'],
    'Agradecer cambia el ritmo de los pensamientos.',
    'La gratitud se parece a abrir una ventana.',
    ['Un día sencillo también puede ser un buen día.', 'optimismo_realista'],
    'Lo que tienes hoy es suficiente para empezar.',
    'Agradecer el camino recorrido le da otra luz al que viene.',
    ['Las pequeñas atenciones hacen una vida más amable.', 'amabilidad'],
    'Hay algo valioso en poder elegir, aunque sea un poco.',
    'Agradecer también es decir: esto importa.',
    'Una noche de buen descanso es un regalo que conviene notar.',
    'La gratitud se cultiva mirando, no exigiendo.',
    'El tiempo compartido es de lo más valioso que se puede dar.',
    'Lo que te conmueve también te dice qué aprecias.',
    'Puedes cerrar los ojos un momento y pensar en algo que agradeces.',
  ],

  calma: [
    'No hace falta resolverlo todo esta mañana.',
    'Puedes bajar el ritmo y seguir a tu manera.',
    ['Una respiración lenta ya es un pequeño descanso.', 'presencia'],
    'La calma también se construye con pausas cortas.',
    'Lo urgente puede esperar a que respires.',
    'El silencio puede ser un buen lugar para ordenar ideas.',
    'Hay preguntas que se aclaran con el paso de las horas.',
    'Puedes hacer una cosa a la vez.',
    'Soltar los hombros también es soltar un poco de peso.',
    'El día se vuelve más amable cuando no lo apuras.',
    'Un pensamiento no es una orden.',
    'La calma no es ausencia de ruido; es encontrar tu lugar en él.',
    'Tomarte un momento antes de responder también es una respuesta.',
    'Mirar por la ventana unos segundos puede despejar la mente.',
    'No todo lo que pasa por tu cabeza pide atención inmediata.',
    'Puedes caminar más despacio y llegar igual.',
    'El agua quieta deja ver el fondo.',
    'Hoy puedes elegir un ritmo que te deje respirar.',
    'Una pausa a tiempo cambia el tono de una conversación.',
    ['Lo que hoy pesa puede verse distinto mañana.', 'esperanza_serena'],
    'La tranquilidad empieza en algo tan simple como sentarte.',
    'Puedes dejar que la prisa pase de largo.',
    ['Respirar hondo es una forma de volver al presente.', 'presencia'],
    'No hace falta llenar cada silencio.',
    'La mente también agradece los espacios en blanco.',
    'Un paso lento sigue siendo un paso.',
    'Puedes posponer la preocupación y atender lo que tienes delante.',
    'El cielo cambia muchas veces en un día, y sigue siendo cielo.',
    'La calma no se exige; se invita.',
    'Escuchar tu respiración puede bajar el volumen del ruido.',
    'Hay tardes que piden menos planes y más aire.',
    'Lo que se hace con calma suele hacerse con cuidado.',
    ['Puedes darle a este momento toda tu atención.', 'presencia'],
    'Un minuto de quietud también cuenta.',
    'Cuando todo corre, puedes elegir caminar.',
    'No es necesario adelantarte a lo que todavía no llega.',
    'El cuerpo sabe descansar si le das la oportunidad.',
    'Entre una cosa y otra cabe una respiración.',
    'La serenidad también se aprende poco a poco.',
    'Puedes dejar el teléfono un rato y mirar alrededor.',
    'Las olas vuelven al mar sin esfuerzo.',
    'A veces la mejor decisión es esperar un poco.',
    ['Puedes escuchar sin preparar la respuesta.', 'empatia'],
    'La calma se contagia, igual que la prisa.',
    ['Hoy puedes hablarte con la suavidad que usarías con alguien que quieres.', 'amabilidad'],
    'Un vaso de agua y un momento de quietud pueden ser un buen comienzo.',
    'Lo que no puedes controlar puede quedarse a un lado un rato.',
    'Las ideas se acomodan cuando les das espacio.',
    'Bajar la voz interior también es una forma de descanso.',
    'Puedes detenerte sin sentir que pierdes el día.',
    'La tranquilidad tiene su propio paso.',
    'Cerrar los ojos un momento puede abrir otra perspectiva.',
    'Hay calma en terminar una cosa antes de empezar otra.',
    'El viento mueve las hojas, pero el árbol sigue en su sitio.',
    'Puedes dejar que esta hora sea más lenta.',
    'No hace falta tener todas las respuestas para estar en paz.',
    'La paciencia contigo también es calma.',
    'El ruido de fuera puede quedarse fuera un rato.',
    'Las cosas importantes rara vez se resuelven con prisa.',
    'Respirar despacio es una forma de cuidarte.',
    'Un paseo corto puede ordenar lo que estaba revuelto.',
    'Hoy puedes elegir lo esencial y dejar lo demás.',
    ['Lo que sientes ahora también va a cambiar.', 'esperanza_serena'],
    'Hay descanso en no tener que demostrar nada.',
    'Puedes mirar tus pensamientos como quien mira pasar nubes.',
    'Una tarde sin prisa también es una tarde bien vivida.',
    'El reloj marca la hora, no tu valor.',
    'Un rato a solas puede ser un buen refugio.',
    'Puedes darte permiso para ir más despacio.',
    'La claridad suele llegar después de la pausa.',
    'Hay noches en que descansar ya es suficiente.',
    ['Escuchar la lluvia es una manera sencilla de estar presente.', 'presencia'],
    'Puedes respirar antes de decidir.',
    'La calma no depende de que todo esté en orden.',
    'Mirar algo verde unos minutos puede devolverte el aliento.',
    'Lo que hoy no se resuelve puede esperar a mañana.',
    'La quietud también es una forma de estar.',
    'Puedes elegir no reaccionar de inmediato.',
    'Un día tranquilo no es un día perdido.',
    'La respiración está disponible en cualquier momento.',
  ],

  identidad: [
    'Eres más que lo que hiciste o dejaste de hacer hoy.',
    'Lo que valoras se nota en las pequeñas decisiones.',
    'Puedes buscar coherencia sin exigirte perfección.',
    'Tu manera de mirar el mundo también tiene valor.',
    'Conocerte es un camino que no termina, y está bien.',
    'Hay fuerza en reconocer lo que te importa.',
    'Tu historia no se resume en un día difícil.',
    'Puedes cambiar de opinión y seguir siendo tú.',
    'Lo que cuidas dice mucho de quién eres.',
    'Tu ritmo también es una forma de ser.',
    'No hace falta parecerte a nadie para estar bien.',
    'Tus preguntas también forman parte de ti.',
    ['Ser amable contigo es una decisión que se renueva.', 'amabilidad'],
    'Puedes escuchar tu propia voz entre tantas otras.',
    'Lo que te da paz es una buena pista sobre ti.',
    'Tus valores pueden guiarte sin volverse una carga.',
    'Hay días para descubrir algo nuevo de ti.',
    'Tu valor no depende de la aprobación de los demás.',
    'Puedes reconocer tus límites con respeto.',
    'Lo que aprendiste te acompaña, aunque no lo veas.',
    'Tus palabras pueden parecerse a lo que sientes.',
    'Ser fiel a ti también es una forma de cuidado.',
    'Tienes derecho a ocupar tu lugar.',
    'Lo que te emociona cuenta algo de quién eres.',
    'Puedes honrar tu pasado sin quedarte a vivir en él.',
    'Tu sensibilidad también es una forma de inteligencia.',
    'Hay valentía en mostrarte tal como eres.',
    'No eres tus errores; eres también lo que haces con ellos.',
    'Elegir con calma es elegir desde ti.',
    ['Tu historia tiene capítulos que todavía no conoces.', 'esperanza_serena'],
    'Puedes decir que no y seguir siendo una buena persona.',
    ['Tu manera de cuidar a otros dice mucho de ti.', 'empatia'],
    'Lo auténtico no necesita gritar.',
    'Puedes darte el mismo respeto que ofreces.',
    'Lo que eliges repetir va dando forma a tus días.',
    'Tienes derecho a cambiar con el tiempo.',
    'Tus raíces y tus sueños pueden convivir.',
    'El valor de una persona se expresa de muchas maneras.',
    'Tus dudas no te hacen menos; te hacen pensar.',
    'Puedes celebrar quién eres hoy, sin esperar a ser otra versión.',
    ['La forma en que tratas a los demás también te define.', 'empatia'],
    ['Tu voz interior puede ser firme y amable a la vez.', 'amabilidad'],
    'Puedes aprender de otros sin dejar de ser tú.',
    'Hay algo tuyo que nadie más puede aportar.',
    'Tus gustos sencillos también hablan de ti.',
    'Saber qué te importa ordena muchas decisiones.',
    'Tu presencia ya aporta algo a quienes te rodean.',
    'Puedes reconocer tus logros sin compararlos.',
    'La honestidad contigo empieza por escucharte.',
    'Tu camino puede ser distinto del de los demás.',
    'Lo que te hace bien merece un lugar en tu día.',
    'Puedes elegir tus palabras con el cuidado con que eliges a tus amistades.',
    'Tu calma también es parte de quien eres.',
    'Hay paz en que tus actos y tus palabras se parezcan.',
    'Puedes mirarte con curiosidad en lugar de con juicio.',
    'Tus límites protegen lo que valoras.',
    'La persona que eres hoy también merece atención.',
    ['Puedes sostener tus ideas y escuchar las de otros.', 'empatia'],
    'Lo que te inspira dice hacia dónde te gustaría ir.',
    'Tu historia es tuya para contarla.',
    'Puedes reconocer lo que has crecido sin medirlo.',
    'Ser tú no requiere permiso.',
    'Tus decisiones de hoy pueden parecerse a lo que valoras.',
    'Hay belleza en las contradicciones humanas.',
    'Puedes descubrirte en lo que haces con gusto.',
    'Tu dignidad no cambia con el resultado del día.',
    'Escucharte es una forma de conocerte.',
    'Seguir descubriendo quién eres también es una forma de paz.',
    'Lo que compartes con otros también te forma.',
    'Tu forma de ver las cosas puede enriquecer una conversación.',
    'Tienes derecho a tus propios tiempos.',
    'Puedes elegir qué historias sobre ti quieres seguir contando.',
    'La manera en que te hablas también construye quién eres.',
    'Lo que defiendes con calma tiene más fuerza.',
    'Tu manera de querer es única.',
    'Puedes reconocer tus talentos sin pedir disculpas.',
    'Cada etapa de la vida muestra algo distinto de ti.',
    'Ser tú, con calma, ya es suficiente por hoy.',
    'Tus gestos cotidianos dicen quién eres más que cualquier título.',
    'Puedes volver a lo que te importa cuando lo pierdas de vista.',
  ],

  aceptacion: [
    'Hoy puede ser un día imperfecto y aun así valioso.',
    'Aceptar no es rendirse; es empezar desde lo que hay.',
    'No hace falta que todo tenga sentido hoy.',
    'Algunas cosas se entienden con el tiempo.',
    'Puedes sentir lo que sientes sin juzgarlo.',
    'Lo que no salió como esperabas también forma parte del camino.',
    'Hay días que se atraviesan, sin más.',
    'Reconocer un límite también es una forma de sabiduría.',
    'Puedes soltar lo que está fuera de tu alcance.',
    ['Las emociones difíciles también pasan.', 'esperanza_serena'],
    'No hace falta estar bien todo el tiempo.',
    'A veces el mejor plan es adaptarse.',
    'Lo que fue ya no pide tu lucha.',
    'Puedes recibir este día como viene.',
    'Aceptar lo que sientes abre espacio para cuidarte.',
    'Las cosas cambian, y tú con ellas.',
    'Hay paz en dejar de discutir con lo que ya pasó.',
    'Puedes decir: esto es lo que hay, y desde aquí sigo.',
    'La tristeza también merece un lugar.',
    'No todo depende de ti, y eso también es un alivio.',
    ['Puedes perdonarte un mal momento.', 'amabilidad'],
    'Una vida con huecos también es una vida plena.',
    ['Un día gris también tiene su luz.', 'optimismo_realista'],
    'Puedes aceptar ayuda sin sentirte en deuda.',
    'Lo que sientes no pide justificación.',
    'A veces lo más sabio es esperar.',
    'Las estaciones cambian sin pedir permiso.',
    'Puedes estar en proceso y estar en paz.',
    ['Aceptar a otros como son también te libera.', 'empatia'],
    'Hay cosas que no se arreglan, se acompañan.',
    'El cansancio también es un mensaje que merece escucha.',
    'Puedes dejar de cargar lo que no te corresponde.',
    'Los planes cambian, y la vida sigue siendo tuya.',
    'Lo que perdiste dejó también lo que aprendiste.',
    'Puedes reconocer el dolor sin quedarte a vivir en él.',
    'Equivocarse es parte de cualquier camino.',
    'Hoy puedes hacer las paces con algo pequeño.',
    'Hay momentos en que lo suficiente es suficiente.',
    'Aceptar el presente es la base de cualquier cambio.',
    'Lo que no puedes cambiar hoy puede dejar de pesar tanto.',
    'Puedes tener días buenos y días difíciles; los dos son tuyos.',
    'La lluvia no se discute; se espera con paciencia.',
    'Aceptar es mirar las cosas tal como son, con amabilidad.',
    ['Puedes dejar que otros tengan su propio ritmo.', 'empatia'],
    'No todas las preguntas tienen respuesta hoy.',
    'Lo que te duele también habla de lo que te importa.',
    'Puedes empezar de nuevo sin borrar lo vivido.',
    'Hay días para avanzar y días para detenerse.',
    'Las despedidas también son parte de la vida.',
    'Puedes aceptar tus emociones sin dejar que decidan por ti.',
    ['Lo imprevisto también puede traer algo bueno.', 'optimismo_realista'],
    'Aceptar tu cansancio es una forma de respeto.',
    'La vida cambia de forma, y puedes cambiar con ella.',
    'Puedes estar en paz sin tenerlo todo bajo control.',
    'Puedes recibir los cambios con curiosidad.',
    'Lo que hiciste con lo que tenías fue suficiente.',
    'Un error no define el día entero.',
    'Aceptar también es dejar de exigirte lo imposible.',
    'Hay tiempos de siembra y tiempos de espera.',
    'Puedes reconocer lo que no sabes sin vergüenza.',
    ['Las personas que quieres también tienen sus límites.', 'empatia'],
    'Hoy puedes dejar algo para otro momento.',
    'La vida no es una línea recta, y no pasa nada.',
    'Puedes sostener dos emociones a la vez.',
    ['Lo que hoy duele puede convertirse en experiencia.', 'esperanza_serena'],
    'Aceptar no es estar de acuerdo con todo; es ver con claridad.',
    'Hay alivio en admitir que algo te supera.',
    'Puedes dejar que el día termine como terminó.',
    'Lo que escapa a tu control también tiene su curso.',
    'No hace falta que hoy sea extraordinario.',
    'Aceptar los propios tiempos es una forma de cuidado.',
    ['Puedes mirar tus errores con la comprensión que ofreces a otros.', 'amabilidad'],
    'Pocas cosas salen exactamente como se planean, y aun así la vida sigue.',
    'Lo que no fue también te trajo hasta aquí.',
    'Puedes soltar una expectativa y quedarte con lo esencial.',
    'Hay paz en decir: hice lo que pude.',
    'La incertidumbre también forma parte de vivir.',
    ['Puedes aceptar el día y aun así esperar algo mejor.', 'esperanza_serena'],
    'Hoy no hace falta ganar ninguna discusión contigo.',
    'Lo que sientes es válido, aunque no lo entiendas del todo.',
  ],

  esfuerzo: [
    'Un paso pequeño también te acerca.',
    'La constancia se construye con días imperfectos.',
    'Lo que empiezas con cariño suele durar más.',
    'Puedes avanzar a tu ritmo, sin compararte.',
    'Intentarlo otra vez también es un logro.',
    'Las cosas valiosas suelen tomar tiempo.',
    'Un poco cada día puede llegar lejos.',
    'Lo que haces con atención tiene su propio valor.',
    'Empezar es a veces lo más difícil, y también lo más valiente.',
    'Puedes hacer hoy una parte, sin cargar con el todo.',
    'El cuidado que pones en algo se nota.',
    'Aprender lleva su tiempo, y está bien.',
    'Las raíces crecen antes de que se vea el árbol.',
    'Lo que repites con cariño termina formando parte de ti.',
    'Puedes descansar y retomar después.',
    'El esfuerzo también incluye saber pausar.',
    'Hacer algo con esmero es una forma de respeto.',
    'La paciencia acompaña a todo lo que crece.',
    'Puedes elegir una cosa y darle tu mejor atención.',
    'Lo que hoy cuesta mañana puede salir con más soltura.',
    'Cada intento te enseña algo.',
    'Avanzar despacio sigue siendo avanzar.',
    'El trabajo hecho con calma deja menos cansancio.',
    'Puedes pedir ayuda y seguir siendo quien lo logra.',
    'La práctica convierte lo difícil en familiar.',
    'Un día de pausa no borra lo que has construido.',
    'Lo importante se cultiva, no se apura.',
    'Puedes poner tu energía en lo que de verdad te importa.',
    'Terminar algo pequeño puede darte impulso.',
    'La perseverancia también sabe ser amable.',
    'Puedes valorar el intento tanto como el resultado.',
    'Los caminos largos se recorren a tramos.',
    'Volver a empezar es parte de cualquier aprendizaje.',
    'Hay mérito en continuar cuando nadie mira.',
    'Puedes ajustar el plan sin abandonar la intención.',
    'El agua constante va dando forma a la piedra.',
    'Puedes dar lo que hoy tienes, y eso basta.',
    'Un esfuerzo sereno sostiene mejor que uno apresurado.',
    'Lo que siembras hoy no tiene prisa por florecer.',
    'Equivocarte mientras aprendes es parte del oficio.',
    'Puedes dividir lo grande en partes amables.',
    'La disciplina también puede ser una forma de cariño.',
    'Hay satisfacción en hacer las cosas con calma.',
    'Cada día ofrece una nueva oportunidad de intentarlo.',
    'Puedes avanzar sin exigirte de más.',
    'Lo que te importa merece tu tiempo, no tu agotamiento.',
    'Seguir adelante a veces es dar un paso más, y nada más.',
    'Tu esfuerzo de hoy cuenta, aunque nadie lo vea.',
    'Un buen comienzo puede ser muy pequeño.',
    'Puedes aprender algo nuevo a cualquier edad.',
    'La constancia es más amable que la prisa.',
    'Hacer tu parte con honestidad también es esforzarse.',
    'Puedes descansar en mitad del camino.',
    'Hay oficios que se aprenden en silencio, día tras día.',
    'Un intento sincero ya tiene valor.',
    'Puedes empezar por lo que tienes a mano.',
    'Las montañas se suben paso a paso.',
    'Puedes cuidar tu energía como cuidas lo que quieres.',
    'Aprender algo nuevo también puede ser un juego.',
    'Puedes elegir el ritmo que te permita continuar.',
    'Hay belleza en el trabajo bien cuidado.',
    'Lo que construyes con paciencia tiene raíces firmes.',
    'Retomar después de una pausa también es constancia.',
    'Puedes dedicarle un rato a algo que te ilusiona.',
    'Lo difícil se vuelve más llevadero cuando se comparte.',
    'Puedes avanzar aunque todavía tengas dudas.',
    'El esfuerzo que te respeta es el que puedes sostener.',
    'Hay días de mucho y días de poco; los dos suman.',
    'Puedes reconocer lo que ya lograste antes de seguir.',
    'Hacer algo por primera vez es una pequeña aventura.',
    'Una práctica diaria no necesita ser larga para ser valiosa.',
    'Puedes elegir la constancia sobre la intensidad.',
    'Las semillas no crecen más rápido porque las miremos.',
    'Lo que haces con cariño deja huella.',
    'Puedes seguir intentándolo a tu manera.',
    'Un paso firme vale más que diez apresurados.',
    ['Ayudar a otros también es una forma de esfuerzo bien puesto.', 'empatia'],
    'Puedes avanzar con calma y llegar lejos.',
    'Tu dedicación de hoy es un regalo para tu yo de mañana.',
    'Cada pequeño avance merece un momento de reconocimiento.',
  ],
})
